"""
Seed lists for the academic identity system.

COUNTRIES   — full ISO-3166-1 alpha-2 list with flag emojis + region.
UNIVERSITIES — approx. 300 well-known institutions across the major markets.
               Strong coverage of Chile, Latin America, US, UK, EU, Asia, Canada, Australia.
               Users can add missing institutions — those get flagged 'pending'.

Schema expected by the loader:
    COUNTRIES:    list[tuple[iso2, name, flag_emoji, region]]
    UNIVERSITIES: list[tuple[name, country_iso, short_name_or_empty]]
"""

# ─────────────────────────────────────────────────────────────────────
# ISO-3166 countries (alpha-2)
# Flags are Unicode regional-indicator sequences. Empty string if your
# terminal doesn't render them; the UI will fall back to the ISO code.
# ─────────────────────────────────────────────────────────────────────

def _flag(iso: str) -> str:
    """Convert ISO-3166 alpha-2 to the flag emoji via regional indicators."""
    if len(iso) != 2:
        return ""
    return "".join(chr(0x1F1E6 + (ord(c.upper()) - ord("A"))) for c in iso)


_RAW_COUNTRIES = [
    # (iso, name, region)
    ("AF", "Afghanistan", "Asia"),
    ("AL", "Albania", "Europe"),
    ("DZ", "Algeria", "Africa"),
    ("AS", "American Samoa", "Oceania"),
    ("AD", "Andorra", "Europe"),
    ("AO", "Angola", "Africa"),
    ("AI", "Anguilla", "Americas"),
    ("AG", "Antigua and Barbuda", "Americas"),
    ("AR", "Argentina", "Americas"),
    ("AM", "Armenia", "Asia"),
    ("AW", "Aruba", "Americas"),
    ("AU", "Australia", "Oceania"),
    ("AT", "Austria", "Europe"),
    ("AZ", "Azerbaijan", "Asia"),
    ("BS", "Bahamas", "Americas"),
    ("BH", "Bahrain", "Asia"),
    ("BD", "Bangladesh", "Asia"),
    ("BB", "Barbados", "Americas"),
    ("BY", "Belarus", "Europe"),
    ("BE", "Belgium", "Europe"),
    ("BZ", "Belize", "Americas"),
    ("BJ", "Benin", "Africa"),
    ("BM", "Bermuda", "Americas"),
    ("BT", "Bhutan", "Asia"),
    ("BO", "Bolivia", "Americas"),
    ("BA", "Bosnia and Herzegovina", "Europe"),
    ("BW", "Botswana", "Africa"),
    ("BR", "Brazil", "Americas"),
    ("BN", "Brunei", "Asia"),
    ("BG", "Bulgaria", "Europe"),
    ("BF", "Burkina Faso", "Africa"),
    ("BI", "Burundi", "Africa"),
    ("KH", "Cambodia", "Asia"),
    ("CM", "Cameroon", "Africa"),
    ("CA", "Canada", "Americas"),
    ("CV", "Cape Verde", "Africa"),
    ("KY", "Cayman Islands", "Americas"),
    ("CF", "Central African Republic", "Africa"),
    ("TD", "Chad", "Africa"),
    ("CL", "Chile", "Americas"),
    ("CN", "China", "Asia"),
    ("CO", "Colombia", "Americas"),
    ("KM", "Comoros", "Africa"),
    ("CG", "Congo", "Africa"),
    ("CD", "Congo (DRC)", "Africa"),
    ("CR", "Costa Rica", "Americas"),
    ("CI", "Côte d'Ivoire", "Africa"),
    ("HR", "Croatia", "Europe"),
    ("CU", "Cuba", "Americas"),
    ("CY", "Cyprus", "Europe"),
    ("CZ", "Czech Republic", "Europe"),
    ("DK", "Denmark", "Europe"),
    ("DJ", "Djibouti", "Africa"),
    ("DM", "Dominica", "Americas"),
    ("DO", "Dominican Republic", "Americas"),
    ("EC", "Ecuador", "Americas"),
    ("EG", "Egypt", "Africa"),
    ("SV", "El Salvador", "Americas"),
    ("GQ", "Equatorial Guinea", "Africa"),
    ("ER", "Eritrea", "Africa"),
    ("EE", "Estonia", "Europe"),
    ("SZ", "Eswatini", "Africa"),
    ("ET", "Ethiopia", "Africa"),
    ("FJ", "Fiji", "Oceania"),
    ("FI", "Finland", "Europe"),
    ("FR", "France", "Europe"),
    ("GA", "Gabon", "Africa"),
    ("GM", "Gambia", "Africa"),
    ("GE", "Georgia", "Asia"),
    ("DE", "Germany", "Europe"),
    ("GH", "Ghana", "Africa"),
    ("GR", "Greece", "Europe"),
    ("GL", "Greenland", "Americas"),
    ("GD", "Grenada", "Americas"),
    ("GU", "Guam", "Oceania"),
    ("GT", "Guatemala", "Americas"),
    ("GG", "Guernsey", "Europe"),
    ("GN", "Guinea", "Africa"),
    ("GW", "Guinea-Bissau", "Africa"),
    ("GY", "Guyana", "Americas"),
    ("HT", "Haiti", "Americas"),
    ("HN", "Honduras", "Americas"),
    ("HK", "Hong Kong", "Asia"),
    ("HU", "Hungary", "Europe"),
    ("IS", "Iceland", "Europe"),
    ("IN", "India", "Asia"),
    ("ID", "Indonesia", "Asia"),
    ("IR", "Iran", "Asia"),
    ("IQ", "Iraq", "Asia"),
    ("IE", "Ireland", "Europe"),
    ("IM", "Isle of Man", "Europe"),
    ("IL", "Israel", "Asia"),
    ("IT", "Italy", "Europe"),
    ("JM", "Jamaica", "Americas"),
    ("JP", "Japan", "Asia"),
    ("JE", "Jersey", "Europe"),
    ("JO", "Jordan", "Asia"),
    ("KZ", "Kazakhstan", "Asia"),
    ("KE", "Kenya", "Africa"),
    ("KI", "Kiribati", "Oceania"),
    ("KW", "Kuwait", "Asia"),
    ("KG", "Kyrgyzstan", "Asia"),
    ("LA", "Laos", "Asia"),
    ("LV", "Latvia", "Europe"),
    ("LB", "Lebanon", "Asia"),
    ("LS", "Lesotho", "Africa"),
    ("LR", "Liberia", "Africa"),
    ("LY", "Libya", "Africa"),
    ("LI", "Liechtenstein", "Europe"),
    ("LT", "Lithuania", "Europe"),
    ("LU", "Luxembourg", "Europe"),
    ("MO", "Macau", "Asia"),
    ("MG", "Madagascar", "Africa"),
    ("MW", "Malawi", "Africa"),
    ("MY", "Malaysia", "Asia"),
    ("MV", "Maldives", "Asia"),
    ("ML", "Mali", "Africa"),
    ("MT", "Malta", "Europe"),
    ("MH", "Marshall Islands", "Oceania"),
    ("MR", "Mauritania", "Africa"),
    ("MU", "Mauritius", "Africa"),
    ("MX", "Mexico", "Americas"),
    ("FM", "Micronesia", "Oceania"),
    ("MD", "Moldova", "Europe"),
    ("MC", "Monaco", "Europe"),
    ("MN", "Mongolia", "Asia"),
    ("ME", "Montenegro", "Europe"),
    ("MA", "Morocco", "Africa"),
    ("MZ", "Mozambique", "Africa"),
    ("MM", "Myanmar", "Asia"),
    ("NA", "Namibia", "Africa"),
    ("NR", "Nauru", "Oceania"),
    ("NP", "Nepal", "Asia"),
    ("NL", "Netherlands", "Europe"),
    ("NZ", "New Zealand", "Oceania"),
    ("NI", "Nicaragua", "Americas"),
    ("NE", "Niger", "Africa"),
    ("NG", "Nigeria", "Africa"),
    ("MK", "North Macedonia", "Europe"),
    ("NO", "Norway", "Europe"),
    ("OM", "Oman", "Asia"),
    ("PK", "Pakistan", "Asia"),
    ("PW", "Palau", "Oceania"),
    ("PS", "Palestine", "Asia"),
    ("PA", "Panama", "Americas"),
    ("PG", "Papua New Guinea", "Oceania"),
    ("PY", "Paraguay", "Americas"),
    ("PE", "Peru", "Americas"),
    ("PH", "Philippines", "Asia"),
    ("PL", "Poland", "Europe"),
    ("PT", "Portugal", "Europe"),
    ("PR", "Puerto Rico", "Americas"),
    ("QA", "Qatar", "Asia"),
    ("RO", "Romania", "Europe"),
    ("RU", "Russia", "Europe"),
    ("RW", "Rwanda", "Africa"),
    ("WS", "Samoa", "Oceania"),
    ("SM", "San Marino", "Europe"),
    ("SA", "Saudi Arabia", "Asia"),
    ("SN", "Senegal", "Africa"),
    ("RS", "Serbia", "Europe"),
    ("SC", "Seychelles", "Africa"),
    ("SL", "Sierra Leone", "Africa"),
    ("SG", "Singapore", "Asia"),
    ("SK", "Slovakia", "Europe"),
    ("SI", "Slovenia", "Europe"),
    ("SB", "Solomon Islands", "Oceania"),
    ("SO", "Somalia", "Africa"),
    ("ZA", "South Africa", "Africa"),
    ("KR", "South Korea", "Asia"),
    ("SS", "South Sudan", "Africa"),
    ("ES", "Spain", "Europe"),
    ("LK", "Sri Lanka", "Asia"),
    ("SD", "Sudan", "Africa"),
    ("SR", "Suriname", "Americas"),
    ("SE", "Sweden", "Europe"),
    ("CH", "Switzerland", "Europe"),
    ("SY", "Syria", "Asia"),
    ("TW", "Taiwan", "Asia"),
    ("TJ", "Tajikistan", "Asia"),
    ("TZ", "Tanzania", "Africa"),
    ("TH", "Thailand", "Asia"),
    ("TL", "Timor-Leste", "Asia"),
    ("TG", "Togo", "Africa"),
    ("TO", "Tonga", "Oceania"),
    ("TT", "Trinidad and Tobago", "Americas"),
    ("TN", "Tunisia", "Africa"),
    ("TR", "Turkey", "Asia"),
    ("TM", "Turkmenistan", "Asia"),
    ("UG", "Uganda", "Africa"),
    ("UA", "Ukraine", "Europe"),
    ("AE", "United Arab Emirates", "Asia"),
    ("GB", "United Kingdom", "Europe"),
    ("US", "United States", "Americas"),
    ("UY", "Uruguay", "Americas"),
    ("UZ", "Uzbekistan", "Asia"),
    ("VU", "Vanuatu", "Oceania"),
    ("VA", "Vatican City", "Europe"),
    ("VE", "Venezuela", "Americas"),
    ("VN", "Vietnam", "Asia"),
    ("YE", "Yemen", "Asia"),
    ("ZM", "Zambia", "Africa"),
    ("ZW", "Zimbabwe", "Africa"),
]

COUNTRIES: list[tuple[str, str, str, str]] = [
    (iso, name, _flag(iso), region) for iso, name, region in _RAW_COUNTRIES
]


# ─────────────────────────────────────────────────────────────────────
# Universities (approx. 300)
# (name, country_iso, short_name_or_empty)
# ─────────────────────────────────────────────────────────────────────
UNIVERSITIES: list[tuple[str, str, str]] = [
    # ───────── Chile (comprehensive, per spec) ─────────
    ("Pontificia Universidad Católica de Chile", "CL", "PUC"),
    ("Universidad de Chile", "CL", "UChile"),
    ("Universidad Técnica Federico Santa María", "CL", "USM"),
    ("Universidad de Santiago de Chile", "CL", "USACH"),
    ("Universidad Adolfo Ibáñez", "CL", "UAI"),
    ("Universidad de Concepción", "CL", "UdeC"),
    ("Universidad Austral de Chile", "CL", "UACh"),
    ("Universidad de los Andes", "CL", "UANDES"),
    ("Universidad Diego Portales", "CL", "UDP"),
    ("Universidad del Desarrollo", "CL", "UDD"),
    ("Universidad Católica del Norte", "CL", "UCN"),
    ("Universidad Católica de Valparaíso", "CL", "PUCV"),
    ("Universidad de Valparaíso", "CL", "UV"),
    ("Universidad de la Frontera", "CL", "UFRO"),
    ("Universidad de Talca", "CL", "UTALCA"),
    ("Universidad Alberto Hurtado", "CL", "UAH"),
    ("Universidad Mayor", "CL", ""),
    ("Universidad San Sebastián", "CL", "USS"),
    ("Universidad Andrés Bello", "CL", "UNAB"),
    ("Universidad Finis Terrae", "CL", "UFT"),
    ("Universidad Central de Chile", "CL", ""),
    ("Universidad Católica del Maule", "CL", "UCM"),
    ("Universidad de La Serena", "CL", "ULS"),
    ("Universidad de Antofagasta", "CL", "UA"),
    ("Universidad Tecnológica Metropolitana", "CL", "UTEM"),

    # ───────── United States ─────────
    ("Massachusetts Institute of Technology", "US", "MIT"),
    ("Stanford University", "US", "Stanford"),
    ("Harvard University", "US", "Harvard"),
    ("California Institute of Technology", "US", "Caltech"),
    ("Princeton University", "US", "Princeton"),
    ("Yale University", "US", "Yale"),
    ("University of Chicago", "US", "UChicago"),
    ("Columbia University", "US", "Columbia"),
    ("University of Pennsylvania", "US", "UPenn"),
    ("Cornell University", "US", "Cornell"),
    ("Brown University", "US", "Brown"),
    ("Dartmouth College", "US", "Dartmouth"),
    ("Duke University", "US", "Duke"),
    ("Johns Hopkins University", "US", "JHU"),
    ("Northwestern University", "US", "NU"),
    ("University of California, Berkeley", "US", "Berkeley"),
    ("University of California, Los Angeles", "US", "UCLA"),
    ("University of California, San Diego", "US", "UCSD"),
    ("University of California, Irvine", "US", "UCI"),
    ("University of California, Davis", "US", "UC Davis"),
    ("University of California, Santa Barbara", "US", "UCSB"),
    ("University of California, Santa Cruz", "US", "UCSC"),
    ("University of California, Riverside", "US", "UCR"),
    ("University of Michigan", "US", "UMich"),
    ("University of Wisconsin–Madison", "US", "UW-Madison"),
    ("University of Illinois Urbana-Champaign", "US", "UIUC"),
    ("University of Texas at Austin", "US", "UT Austin"),
    ("University of Washington", "US", "UW"),
    ("Carnegie Mellon University", "US", "CMU"),
    ("Georgia Institute of Technology", "US", "Georgia Tech"),
    ("University of North Carolina at Chapel Hill", "US", "UNC"),
    ("New York University", "US", "NYU"),
    ("Boston University", "US", "BU"),
    ("Boston College", "US", "BC"),
    ("Northeastern University", "US", "NEU"),
    ("Vanderbilt University", "US", "Vanderbilt"),
    ("Rice University", "US", "Rice"),
    ("Washington University in St. Louis", "US", "WashU"),
    ("Emory University", "US", "Emory"),
    ("University of Notre Dame", "US", "ND"),
    ("University of Southern California", "US", "USC"),
    ("Purdue University", "US", "Purdue"),
    ("Pennsylvania State University", "US", "Penn State"),
    ("Ohio State University", "US", "OSU"),
    ("Michigan State University", "US", "MSU"),
    ("Arizona State University", "US", "ASU"),
    ("University of Arizona", "US", "U of A"),
    ("University of Florida", "US", "UF"),
    ("Florida State University", "US", "FSU"),
    ("University of Miami", "US", "UMiami"),
    ("Texas A&M University", "US", "TAMU"),
    ("Rutgers University", "US", "Rutgers"),
    ("University of Maryland, College Park", "US", "UMD"),
    ("Virginia Tech", "US", "VT"),
    ("University of Virginia", "US", "UVA"),
    ("Georgetown University", "US", "Georgetown"),
    ("George Washington University", "US", "GWU"),
    ("Tufts University", "US", "Tufts"),
    ("Brandeis University", "US", "Brandeis"),
    ("Case Western Reserve University", "US", "CWRU"),
    ("University of Rochester", "US", "UR"),
    ("Wake Forest University", "US", "Wake Forest"),
    ("University of Pittsburgh", "US", "Pitt"),
    ("University of Minnesota", "US", "UMN"),
    ("University of Colorado Boulder", "US", "CU Boulder"),
    ("University of Utah", "US", "UU"),
    ("Brigham Young University", "US", "BYU"),
    ("Stevens Institute of Technology", "US", "Stevens"),
    ("Rensselaer Polytechnic Institute", "US", "RPI"),
    ("Lehigh University", "US", "Lehigh"),
    ("University of Connecticut", "US", "UConn"),
    ("University of Iowa", "US", "UIowa"),
    ("Indiana University Bloomington", "US", "IU"),
    ("University of Georgia", "US", "UGA"),
    ("University of South Carolina", "US", "USC-SC"),
    ("Clemson University", "US", "Clemson"),
    ("Auburn University", "US", "Auburn"),
    ("University of Kansas", "US", "KU"),
    ("Kansas State University", "US", "K-State"),
    ("University of Kentucky", "US", "UK"),
    ("University of Tennessee", "US", "UT"),
    ("University of Missouri", "US", "Mizzou"),
    ("University of Oregon", "US", "UO"),
    ("Oregon State University", "US", "OSU-OR"),
    ("University of Nevada, Las Vegas", "US", "UNLV"),
    ("San Diego State University", "US", "SDSU"),
    ("San Jose State University", "US", "SJSU"),
    ("Cal Poly San Luis Obispo", "US", "Cal Poly"),
    ("Babson College", "US", "Babson"),
    ("Bentley University", "US", "Bentley"),
    ("Hult International Business School", "US", "Hult"),

    # ───────── United Kingdom ─────────
    ("University of Oxford", "GB", "Oxford"),
    ("University of Cambridge", "GB", "Cambridge"),
    ("Imperial College London", "GB", "Imperial"),
    ("University College London", "GB", "UCL"),
    ("London School of Economics", "GB", "LSE"),
    ("King's College London", "GB", "KCL"),
    ("University of Edinburgh", "GB", "UoE"),
    ("University of Manchester", "GB", "UoM"),
    ("University of Bristol", "GB", "Bristol"),
    ("University of Warwick", "GB", "Warwick"),
    ("University of Glasgow", "GB", "Glasgow"),
    ("University of Birmingham", "GB", "UoB"),
    ("University of Sheffield", "GB", "Sheffield"),
    ("University of Leeds", "GB", "Leeds"),
    ("University of Nottingham", "GB", "Nottingham"),
    ("University of Southampton", "GB", "Soton"),
    ("University of St Andrews", "GB", "St Andrews"),
    ("Durham University", "GB", "Durham"),
    ("Queen Mary University of London", "GB", "QMUL"),
    ("Lancaster University", "GB", "Lancaster"),
    ("University of Exeter", "GB", "Exeter"),
    ("University of York", "GB", "York"),
    ("Cardiff University", "GB", "Cardiff"),
    ("University of Liverpool", "GB", "Liverpool"),
    ("Newcastle University", "GB", "Newcastle"),

    # ───────── Canada ─────────
    ("University of Toronto", "CA", "UofT"),
    ("McGill University", "CA", "McGill"),
    ("University of British Columbia", "CA", "UBC"),
    ("University of Waterloo", "CA", "UWaterloo"),
    ("McMaster University", "CA", "McMaster"),
    ("University of Alberta", "CA", "UAlberta"),
    ("Queen's University", "CA", "Queen's"),
    ("Western University", "CA", "Western"),
    ("University of Montreal", "CA", "UdeM"),
    ("Simon Fraser University", "CA", "SFU"),
    ("University of Ottawa", "CA", "uOttawa"),
    ("Université Laval", "CA", "Laval"),
    ("Dalhousie University", "CA", "Dal"),
    ("University of Calgary", "CA", "UCalgary"),
    ("Concordia University", "CA", "Concordia"),
    ("York University", "CA", "York"),
    ("Ryerson University", "CA", "Ryerson"),

    # ───────── Australia / NZ ─────────
    ("University of Melbourne", "AU", "Melbourne"),
    ("Australian National University", "AU", "ANU"),
    ("University of Sydney", "AU", "USyd"),
    ("University of New South Wales", "AU", "UNSW"),
    ("University of Queensland", "AU", "UQ"),
    ("Monash University", "AU", "Monash"),
    ("University of Western Australia", "AU", "UWA"),
    ("University of Adelaide", "AU", "Adelaide"),
    ("University of Technology Sydney", "AU", "UTS"),
    ("University of Auckland", "NZ", "UoA"),
    ("University of Otago", "NZ", "Otago"),
    ("Victoria University of Wellington", "NZ", "VUW"),

    # ───────── China / Hong Kong / Taiwan ─────────
    ("Tsinghua University", "CN", "Tsinghua"),
    ("Peking University", "CN", "PKU"),
    ("Fudan University", "CN", "Fudan"),
    ("Shanghai Jiao Tong University", "CN", "SJTU"),
    ("Zhejiang University", "CN", "ZJU"),
    ("University of Science and Technology of China", "CN", "USTC"),
    ("Nanjing University", "CN", "Nanjing"),
    ("Sun Yat-sen University", "CN", "SYSU"),
    ("Wuhan University", "CN", "WHU"),
    ("University of Hong Kong", "HK", "HKU"),
    ("Hong Kong University of Science and Technology", "HK", "HKUST"),
    ("Chinese University of Hong Kong", "HK", "CUHK"),
    ("City University of Hong Kong", "HK", "CityU"),
    ("National Taiwan University", "TW", "NTU"),
    ("National Tsing Hua University", "TW", "NTHU"),
    ("National Cheng Kung University", "TW", "NCKU"),

    # ───────── Japan / Korea ─────────
    ("University of Tokyo", "JP", "Todai"),
    ("Kyoto University", "JP", "Kyodai"),
    ("Osaka University", "JP", "Handai"),
    ("Tokyo Institute of Technology", "JP", "Tokyo Tech"),
    ("Tohoku University", "JP", "Tohoku"),
    ("Nagoya University", "JP", "Nagoya"),
    ("Keio University", "JP", "Keio"),
    ("Waseda University", "JP", "Waseda"),
    ("Seoul National University", "KR", "SNU"),
    ("KAIST", "KR", "KAIST"),
    ("Yonsei University", "KR", "Yonsei"),
    ("Korea University", "KR", "KU"),
    ("POSTECH", "KR", "POSTECH"),
    ("Sungkyunkwan University", "KR", "SKKU"),

    # ───────── Singapore / India / SE Asia ─────────
    ("National University of Singapore", "SG", "NUS"),
    ("Nanyang Technological University", "SG", "NTU"),
    ("Singapore Management University", "SG", "SMU"),
    ("Indian Institute of Technology Bombay", "IN", "IIT Bombay"),
    ("Indian Institute of Technology Delhi", "IN", "IIT Delhi"),
    ("Indian Institute of Technology Madras", "IN", "IIT Madras"),
    ("Indian Institute of Technology Kanpur", "IN", "IIT Kanpur"),
    ("Indian Institute of Technology Kharagpur", "IN", "IIT KGP"),
    ("Indian Institute of Science", "IN", "IISc"),
    ("Indian Institute of Technology Roorkee", "IN", "IIT Roorkee"),
    ("Indian Institute of Technology Guwahati", "IN", "IIT G"),
    ("Delhi University", "IN", "DU"),
    ("BITS Pilani", "IN", "BITS"),
    ("University of Malaya", "MY", "UM"),
    ("Chulalongkorn University", "TH", "Chula"),
    ("Mahidol University", "TH", ""),
    ("University of the Philippines", "PH", "UP"),
    ("Ateneo de Manila University", "PH", "Ateneo"),
    ("De La Salle University", "PH", "DLSU"),
    ("University of Indonesia", "ID", "UI"),
    ("Institut Teknologi Bandung", "ID", "ITB"),
    ("Vietnam National University", "VN", "VNU"),

    # ───────── Europe (non-UK) ─────────
    ("ETH Zurich", "CH", "ETH"),
    ("EPFL", "CH", "EPFL"),
    ("University of Zurich", "CH", "UZH"),
    ("Technical University of Munich", "DE", "TUM"),
    ("Ludwig Maximilian University of Munich", "DE", "LMU"),
    ("Heidelberg University", "DE", ""),
    ("Humboldt University of Berlin", "DE", "HU Berlin"),
    ("Free University of Berlin", "DE", "FU Berlin"),
    ("RWTH Aachen University", "DE", "RWTH"),
    ("Delft University of Technology", "NL", "TU Delft"),
    ("University of Amsterdam", "NL", "UvA"),
    ("Utrecht University", "NL", ""),
    ("Leiden University", "NL", ""),
    ("Erasmus University Rotterdam", "NL", "EUR"),
    ("KU Leuven", "BE", "KUL"),
    ("Ghent University", "BE", "UGent"),
    ("Université catholique de Louvain", "BE", "UCLouvain"),
    ("Sorbonne University", "FR", "Sorbonne"),
    ("École Polytechnique", "FR", "X"),
    ("Sciences Po", "FR", ""),
    ("École Normale Supérieure", "FR", "ENS"),
    ("HEC Paris", "FR", "HEC"),
    ("INSEAD", "FR", "INSEAD"),
    ("PSL University", "FR", "PSL"),
    ("Université Paris-Saclay", "FR", ""),
    ("Bocconi University", "IT", "Bocconi"),
    ("University of Bologna", "IT", "UniBo"),
    ("Sapienza University of Rome", "IT", "Sapienza"),
    ("Politecnico di Milano", "IT", "Polimi"),
    ("University of Milan", "IT", "UniMi"),
    ("IE University", "ES", "IE"),
    ("IESE Business School", "ES", "IESE"),
    ("Universidad Autónoma de Madrid", "ES", "UAM"),
    ("Universidad Complutense de Madrid", "ES", "UCM"),
    ("Universidad de Barcelona", "ES", "UB"),
    ("Universidad Politécnica de Madrid", "ES", "UPM"),
    ("Universidad Pompeu Fabra", "ES", "UPF"),
    ("University of Lisbon", "PT", "UL"),
    ("NOVA University Lisbon", "PT", "NOVA"),
    ("University of Porto", "PT", "UP"),
    ("Trinity College Dublin", "IE", "TCD"),
    ("University College Dublin", "IE", "UCD"),
    ("Karolinska Institute", "SE", "KI"),
    ("KTH Royal Institute of Technology", "SE", "KTH"),
    ("Lund University", "SE", ""),
    ("Uppsala University", "SE", ""),
    ("University of Copenhagen", "DK", "KU"),
    ("Technical University of Denmark", "DK", "DTU"),
    ("University of Oslo", "NO", "UiO"),
    ("Norwegian University of Science and Technology", "NO", "NTNU"),
    ("University of Helsinki", "FI", ""),
    ("Aalto University", "FI", "Aalto"),
    ("University of Warsaw", "PL", "UW"),
    ("Jagiellonian University", "PL", ""),
    ("Charles University", "CZ", ""),
    ("Vienna University of Economics and Business", "AT", "WU"),
    ("University of Vienna", "AT", ""),
    ("Moscow State University", "RU", "MSU"),
    ("Higher School of Economics", "RU", "HSE"),

    # ───────── Latin America (non-Chile) ─────────
    ("Universidad Nacional Autónoma de México", "MX", "UNAM"),
    ("Tecnológico de Monterrey", "MX", "Tec"),
    ("Instituto Politécnico Nacional", "MX", "IPN"),
    ("Universidad Iberoamericana", "MX", "Ibero"),
    ("Universidad de las Américas Puebla", "MX", "UDLAP"),
    ("ITAM", "MX", "ITAM"),
    ("Universidad Anáhuac", "MX", "Anáhuac"),
    ("Universidad de Buenos Aires", "AR", "UBA"),
    ("Universidad Torcuato Di Tella", "AR", "UTDT"),
    ("Universidad de San Andrés", "AR", "UdeSA"),
    ("Universidad Austral", "AR", ""),
    ("Pontifícia Universidade Católica do Rio de Janeiro", "BR", "PUC-Rio"),
    ("Universidade de São Paulo", "BR", "USP"),
    ("Universidade Federal do Rio de Janeiro", "BR", "UFRJ"),
    ("Universidade Estadual de Campinas", "BR", "Unicamp"),
    ("Universidade Federal de Minas Gerais", "BR", "UFMG"),
    ("Fundação Getulio Vargas", "BR", "FGV"),
    ("Universidade de Brasília", "BR", "UnB"),
    ("Universidad de los Andes", "CO", "Uniandes"),
    ("Universidad Nacional de Colombia", "CO", "UNAL"),
    ("Pontificia Universidad Javeriana", "CO", "Javeriana"),
    ("Universidad del Rosario", "CO", ""),
    ("Universidad EAFIT", "CO", "EAFIT"),
    ("Universidad de Antioquia", "CO", "UdeA"),
    ("Pontificia Universidad Católica del Perú", "PE", "PUCP"),
    ("Universidad Nacional Mayor de San Marcos", "PE", "UNMSM"),
    ("Universidad del Pacífico", "PE", "UP"),
    ("Universidad de Lima", "PE", "ULima"),
    ("Universidad San Francisco de Quito", "EC", "USFQ"),
    ("Escuela Politécnica Nacional", "EC", "EPN"),
    ("Universidad de la República", "UY", "UdelaR"),
    ("Universidad ORT Uruguay", "UY", "ORT"),
    ("Universidad de Costa Rica", "CR", "UCR"),
    ("Instituto Tecnológico de Costa Rica", "CR", "TEC"),

    # ───────── Middle East / Africa ─────────
    ("Technion – Israel Institute of Technology", "IL", "Technion"),
    ("Tel Aviv University", "IL", "TAU"),
    ("Hebrew University of Jerusalem", "IL", "HUJI"),
    ("Weizmann Institute of Science", "IL", "Weizmann"),
    ("King Fahd University of Petroleum and Minerals", "SA", "KFUPM"),
    ("King Abdullah University of Science and Technology", "SA", "KAUST"),
    ("King Saud University", "SA", "KSU"),
    ("American University of Beirut", "LB", "AUB"),
    ("American University in Cairo", "EG", "AUC"),
    ("Cairo University", "EG", ""),
    ("Bogazici University", "TR", "BU"),
    ("Middle East Technical University", "TR", "METU"),
    ("Koç University", "TR", "Koç"),
    ("Bilkent University", "TR", "Bilkent"),
    ("University of Cape Town", "ZA", "UCT"),
    ("Stellenbosch University", "ZA", "SU"),
    ("University of the Witwatersrand", "ZA", "Wits"),
    ("University of Pretoria", "ZA", "UP"),
    ("University of Johannesburg", "ZA", "UJ"),
    ("University of Nairobi", "KE", ""),
    ("University of Cairo", "EG", ""),
    ("Makerere University", "UG", ""),
    ("University of Ghana", "GH", ""),
    ("University of Lagos", "NG", "UNILAG"),
    ("Covenant University", "NG", ""),
]
