"""
Seed lists for the academic identity system.

COUNTRIES   — full ISO-3166-1 alpha-2 list with flag emojis + region.
UNIVERSITIES — approx. 300 well-known institutions across the major markets.
               Strong coverage of Chile, Latin America, US, UK, EU, Asia, Canada, Australia.
               Users can add missing institutions — those get flagged 'pending'.

Schema expected by the loader:
    COUNTRIES:    list[tuple[iso2, name, flag_emoji, region]]
    UNIVERSITIES: list[tuple[name, country_iso, short_name_or_empty]]
"""

# ─────────────────────────────────────────────────────────────────────
# ISO-3166 countries (alpha-2)
# Flags are Unicode regional-indicator sequences. Empty string if your
# terminal doesn't render them; the UI will fall back to the ISO code.
# ─────────────────────────────────────────────────────────────────────

def _flag(iso: str) -> str:
    """Convert ISO-3166 alpha-2 to the flag emoji via regional indicators."""
    if len(iso) != 2:
        return ""
    return "".join(chr(0x1F1E6 + (ord(c.upper()) - ord("A"))) for c in iso)


_RAW_COUNTRIES = [
    # (iso, name, region)
    ("AF", "Afghanistan", "Asia"),
    ("AL", "Albania", "Europe"),
    ("DZ", "Algeria", "Africa"),
    ("AS", "American Samoa", "Oceania"),
    ("AD", "Andorra", "Europe"),
    ("AO", "Angola", "Africa"),
    ("AI", "Anguilla", "Americas"),
    ("AG", "Antigua and Barbuda", "Americas"),
    ("AR", "Argentina", "Americas"),
    ("AM", "Armenia", "Asia"),
    ("AW", "Aruba", "Americas"),
    ("AU", "Australia", "Oceania"),
    ("AT", "Austria", "Europe"),
    ("AZ", "Azerbaijan", "Asia"),
    ("BS", "Bahamas", "Americas"),
    ("BH", "Bahrain", "Asia"),
    ("BD", "Bangladesh", "Asia"),
    ("BB", "Barbados", "Americas"),
    ("BY", "Belarus", "Europe"),
    ("BE", "Belgium", "Europe"),
    ("BZ", "Belize", "Americas"),
    ("BJ", "Benin", "Africa"),
    ("BM", "Bermuda", "Americas"),
    ("BT", "Bhutan", "Asia"),
    ("BO", "Bolivia", "Americas"),
    ("BA", "Bosnia and Herzegovina", "Europe"),
    ("BW", "Botswana", "Africa"),
    ("BR", "Brazil", "Americas"),
    ("BN", "Brunei", "Asia"),
    ("BG", "Bulgaria", "Europe"),
    ("BF", "Burkina Faso", "Africa"),
    ("BI", "Burundi", "Africa"),
    ("KH", "Cambodia", "Asia"),
    ("CM", "Cameroon", "Africa"),
    ("CA", "Canada", "Americas"),
    ("CV", "Cape Verde", "Africa"),
    ("KY", "Cayman Islands", "Americas"),
    ("CF", "Central African Republic", "Africa"),
    ("TD", "Chad", "Africa"),
    ("CL", "Chile", "Americas"),
    ("CN", "China", "Asia"),
    ("CO", "Colombia", "Americas"),
    ("KM", "Comoros", "Africa"),
    ("CG", "Congo", "Africa"),
    ("CD", "Congo (DRC)", "Africa"),
    ("CR", "Costa Rica", "Americas"),
    ("CI", "Côte d'Ivoire", "Africa"),
    ("HR", "Croatia", "Europe"),
    ("CU", "Cuba", "Americas"),
    ("CY", "Cyprus", "Europe"),
    ("CZ", "Czech Republic", "Europe"),
    ("DK", "Denmark", "Europe"),
    ("DJ", "Djibouti", "Africa"),
    ("DM", "Dominica", "Americas"),
    ("DO", "Dominican Republic", "Americas"),
    ("EC", "Ecuador", "Americas"),
    ("EG", "Egypt", "Africa"),
    ("SV", "El Salvador", "Americas"),
    ("GQ", "Equatorial Guinea", "Africa"),
    ("ER", "Eritrea", "Africa"),
    ("EE", "Estonia", "Europe"),
    ("SZ", "Eswatini", "Africa"),
    ("ET", "Ethiopia", "Africa"),
    ("FJ", "Fiji", "Oceania"),
    ("FI", "Finland", "Europe"),
    ("FR", "France", "Europe"),
    ("GA", "Gabon", "Africa"),
    ("GM", "Gambia", "Africa"),
    ("GE", "Georgia", "Asia"),
    ("DE", "Germany", "Europe"),
    ("GH", "Ghana", "Africa"),
    ("GR", "Greece", "Europe"),
    ("GL", "Greenland", "Americas"),
    ("GD", "Grenada", "Americas"),
    ("GU", "Guam", "Oceania"),
    ("GT", "Guatemala", "Americas"),
    ("GG", "Guernsey", "Europe"),
    ("GN", "Guinea", "Africa"),
    ("GW", "Guinea-Bissau", "Africa"),
    ("GY", "Guyana", "Americas"),
    ("HT", "Haiti", "Americas"),
    ("HN", "Honduras", "Americas"),
    ("HK", "Hong Kong", "Asia"),
    ("HU", "Hungary", "Europe"),
    ("IS", "Iceland", "Europe"),
    ("IN", "India", "Asia"),
    ("ID", "Indonesia", "Asia"),
    ("IR", "Iran", "Asia"),
    ("IQ", "Iraq", "Asia"),
    ("IE", "Ireland", "Europe"),
    ("IM", "Isle of Man", "Europe"),
    ("IL", "Israel", "Asia"),
    ("IT", "Italy", "Europe"),
    ("JM", "Jamaica", "Americas"),
    ("JP", "Japan", "Asia"),
    ("JE", "Jersey", "Europe"),
    ("JO", "Jordan", "Asia"),
    ("KZ", "Kazakhstan", "Asia"),
    ("KE", "Kenya", "Africa"),
    ("KI", "Kiribati", "Oceania"),
    ("KW", "Kuwait", "Asia"),
    ("KG", "Kyrgyzstan", "Asia"),
    ("LA", "Laos", "Asia"),
    ("LV", "Latvia", "Europe"),
    ("LB", "Lebanon", "Asia"),
    ("LS", "Lesotho", "Africa"),
    ("LR", "Liberia", "Africa"),
    ("LY", "Libya", "Africa"),
    ("LI", "Liechtenstein", "Europe"),
    ("LT", "Lithuania", "Europe"),
    ("LU", "Luxembourg", "Europe"),
    ("MO", "Macau", "Asia"),
    ("MG", "Madagascar", "Africa"),
    ("MW", "Malawi", "Africa"),
    ("MY", "Malaysia", "Asia"),
    ("MV", "Maldives", "Asia"),
    ("ML", "Mali", "Africa"),
    ("MT", "Malta", "Europe"),
    ("MH", "Marshall Islands", "Oceania"),
    ("MR", "Mauritania", "Africa"),
    ("MU", "Mauritius", "Africa"),
    ("MX", "Mexico", "Americas"),
    ("FM", "Micronesia", "Oceania"),
    ("MD", "Moldova", "Europe"),
    ("MC", "Monaco", "Europe"),
    ("MN", "Mongolia", "Asia"),
    ("ME", "Montenegro", "Europe"),
    ("MA", "Morocco", "Africa"),
    ("MZ", "Mozambique", "Africa"),
    ("MM", "Myanmar", "Asia"),
    ("NA", "Namibia", "Africa"),
    ("NR", "Nauru", "Oceania"),
    ("NP", "Nepal", "Asia"),
    ("NL", "Netherlands", "Europe"),
    ("NZ", "New Zealand", "Oceania"),
    ("NI", "Nicaragua", "Americas"),
    ("NE", "Niger", "Africa"),
    ("NG", "Nigeria", "Africa"),
    ("MK", "North Macedonia", "Europe"),
    ("NO", "Norway", "Europe"),
    ("OM", "Oman", "Asia"),
    ("PK", "Pakistan", "Asia"),
    ("PW", "Palau", "Oceania"),
    ("PS", "Palestine", "Asia"),
    ("PA", "Panama", "Americas"),
    ("PG", "Papua New Guinea", "Oceania"),
    ("PY", "Paraguay", "Americas"),
    ("PE", "Peru", "Americas"),
    ("PH", "Philippines", "Asia"),
    ("PL", "Poland", "Europe"),
    ("PT", "Portugal", "Europe"),
    ("PR", "Puerto Rico", "Americas"),
    ("QA", "Qatar", "Asia"),
    ("RO", "Romania", "Europe"),
    ("RU", "Russia", "Europe"),
    ("RW", "Rwanda", "Africa"),
    ("WS", "Samoa", "Oceania"),
    ("SM", "San Marino", "Europe"),
    ("SA", "Saudi Arabia", "Asia"),
    ("SN", "Senegal", "Africa"),
    ("RS", "Serbia", "Europe"),
    ("SC", "Seychelles", "Africa"),
    ("SL", "Sierra Leone", "Africa"),
    ("SG", "Singapore", "Asia"),
    ("SK", "Slovakia", "Europe"),
    ("SI", "Slovenia", "Europe"),
    ("SB", "Solomon Islands", "Oceania"),
    ("SO", "Somalia", "Africa"),
    ("ZA", "South Africa", "Africa"),
    ("KR", "South Korea", "Asia"),
    ("SS", "South Sudan", "Africa"),
    ("ES", "Spain", "Europe"),
    ("LK", "Sri Lanka", "Asia"),
    ("SD", "Sudan", "Africa"),
    ("SR", "Suriname", "Americas"),
    ("SE", "Sweden", "Europe"),
    ("CH", "Switzerland", "Europe"),
    ("SY", "Syria", "Asia"),
    ("TW", "Taiwan", "Asia"),
    ("TJ", "Tajikistan", "Asia"),
    ("TZ", "Tanzania", "Africa"),
    ("TH", "Thailand", "Asia"),
    ("TL", "Timor-Leste", "Asia"),
    ("TG", "Togo", "Africa"),
    ("TO", "Tonga", "Oceania"),
    ("TT", "Trinidad and Tobago", "Americas"),
    ("TN", "Tunisia", "Africa"),
    ("TR", "Turkey", "Asia"),
    ("TM", "Turkmenistan", "Asia"),
    ("UG", "Uganda", "Africa"),
    ("UA", "Ukraine", "Europe"),
    ("AE", "United Arab Emirates", "Asia"),
    ("GB", "United Kingdom", "Europe"),
    ("US", "United States", "Americas"),
    ("UY", "Uruguay", "Americas"),
    ("UZ", "Uzbekistan", "Asia"),
    ("VU", "Vanuatu", "Oceania"),
    ("VA", "Vatican City", "Europe"),
    ("VE", "Venezuela", "Americas"),
    ("VN", "Vietnam", "Asia"),
    ("YE", "Yemen", "Asia"),
    ("ZM", "Zambia", "Africa"),
    ("ZW", "Zimbabwe", "Africa"),
]

COUNTRIES: list[tuple[str, str, str, str]] = [
    (iso, name, _flag(iso), region) for iso, name, region in _RAW_COUNTRIES
]


# ─────────────────────────────────────────────────────────────────────
# Universities (approx. 300)
# (name, country_iso, short_name_or_empty)
# ─────────────────────────────────────────────────────────────────────
UNIVERSITIES: list[tuple[str, str, str]] = [
    # ───────── Chile (comprehensive, per spec) ─────────
    ("Pontificia Universidad Católica de Chile", "CL", "PUC"),
    ("Universidad de Chile", "CL", "UChile"),
    ("Universidad Técnica Federico Santa María", "CL", "USM"),
    ("Universidad de Santiago de Chile", "CL", "USACH"),
    ("Universidad Adolfo Ibáñez", "CL", "UAI"),
    ("Universidad de Concepción", "CL", "UdeC"),
    ("Universidad Austral de Chile", "CL", "UACh"),
    ("Universidad de los Andes", "CL", "UANDES"),
    ("Universidad Diego Portales", "CL", "UDP"),
    ("Universidad del Desarrollo", "CL", "UDD"),
    ("Universidad Católica del Norte", "CL", "UCN"),
    ("Universidad Católica de Valparaíso", "CL", "PUCV"),
    ("Universidad de Valparaíso", "CL", "UV"),
    ("Universidad de la Frontera", "CL", "UFRO"),
    ("Universidad de Talca", "CL", "UTALCA"),
    ("Universidad Alberto Hurtado", "CL", "UAH"),
    ("Universidad Mayor", "CL", ""),
    ("Universidad San Sebastián", "CL", "USS"),
    ("Universidad Andrés Bello", "CL", "UNAB"),
    ("Universidad Finis Terrae", "CL", "UFT"),
    ("Universidad Central de Chile", "CL", ""),
    ("Universidad Católica del Maule", "CL", "UCM"),
    ("Universidad de La Serena", "CL", "ULS"),
    ("Universidad de Antofagasta", "CL", "UA"),
    ("Universidad Tecnológica Metropolitana", "CL", "UTEM"),
    ("Duoc UC", "CL", "Duoc"),
    ("Instituto Profesional AIEP", "CL", "AIEP"),
    ("INACAP", "CL", "INACAP"),
    ("Universidad Bernardo O'Higgins", "CL", "UBO"),
    ("Universidad Autónoma de Chile", "CL", "UA"),
    ("Universidad Católica de la Santísima Concepción", "CL", "UCSC"),
    ("Universidad Católica del Norte (Coquimbo)", "CL", "UCN"),
    ("Universidad de Atacama", "CL", "UDA"),
    ("Universidad de Magallanes", "CL", "UMAG"),
    ("Universidad de Los Lagos", "CL", "ULagos"),
    ("Universidad de Playa Ancha", "CL", "UPLA"),
    ("Universidad de Tarapacá", "CL", "UTA"),
    ("Universidad Arturo Prat", "CL", "UNAP"),
    ("Universidad Metropolitana de Ciencias de la Educación", "CL", "UMCE"),
    ("Universidad de Las Américas", "CL", "UDLA"),
    ("Universidad Santo Tomás", "CL", "UST"),
    ("Universidad SEK", "CL", "USEK"),

    # ───────── United States ─────────
    ("Massachusetts Institute of Technology", "US", "MIT"),
    ("Stanford University", "US", "Stanford"),
    ("Harvard University", "US", "Harvard"),
    ("California Institute of Technology", "US", "Caltech"),
    ("Princeton University", "US", "Princeton"),
    ("Yale University", "US", "Yale"),
    ("University of Chicago", "US", "UChicago"),
    ("Columbia University", "US", "Columbia"),
    ("University of Pennsylvania", "US", "UPenn"),
    ("Cornell University", "US", "Cornell"),
    ("Brown University", "US", "Brown"),
    ("Dartmouth College", "US", "Dartmouth"),
    ("Duke University", "US", "Duke"),
    ("Johns Hopkins University", "US", "JHU"),
    ("Northwestern University", "US", "NU"),
    ("University of California, Berkeley", "US", "Berkeley"),
    ("University of California, Los Angeles", "US", "UCLA"),
    ("University of California, San Diego", "US", "UCSD"),
    ("University of California, Irvine", "US", "UCI"),
    ("University of California, Davis", "US", "UC Davis"),
    ("University of California, Santa Barbara", "US", "UCSB"),
    ("University of California, Santa Cruz", "US", "UCSC"),
    ("University of California, Riverside", "US", "UCR"),
    ("University of Michigan", "US", "UMich"),
    ("University of Wisconsin–Madison", "US", "UW-Madison"),
    ("University of Illinois Urbana-Champaign", "US", "UIUC"),
    ("University of Texas at Austin", "US", "UT Austin"),
    ("University of Washington", "US", "UW"),
    ("Carnegie Mellon University", "US", "CMU"),
    ("Georgia Institute of Technology", "US", "Georgia Tech"),
    ("University of North Carolina at Chapel Hill", "US", "UNC"),
    ("New York University", "US", "NYU"),
    ("Boston University", "US", "BU"),
    ("Boston College", "US", "BC"),
    ("Northeastern University", "US", "NEU"),
    ("Vanderbilt University", "US", "Vanderbilt"),
    ("Rice University", "US", "Rice"),
    ("Washington University in St. Louis", "US", "WashU"),
    ("Emory University", "US", "Emory"),
    ("University of Notre Dame", "US", "ND"),
    ("University of Southern California", "US", "USC"),
    ("Purdue University", "US", "Purdue"),
    ("Pennsylvania State University", "US", "Penn State"),
    ("Ohio State University", "US", "OSU"),
    ("Michigan State University", "US", "MSU"),
    ("Arizona State University", "US", "ASU"),
    ("University of Arizona", "US", "U of A"),
    ("University of Florida", "US", "UF"),
    ("Florida State University", "US", "FSU"),
    ("University of Miami", "US", "UMiami"),
    ("Texas A&M University", "US", "TAMU"),
    ("Rutgers University", "US", "Rutgers"),
    ("University of Maryland, College Park", "US", "UMD"),
    ("Virginia Tech", "US", "VT"),
    ("University of Virginia", "US", "UVA"),
    ("Georgetown University", "US", "Georgetown"),
    ("George Washington University", "US", "GWU"),
    ("Tufts University", "US", "Tufts"),
    ("Brandeis University", "US", "Brandeis"),
    ("Case Western Reserve University", "US", "CWRU"),
    ("University of Rochester", "US", "UR"),
    ("Wake Forest University", "US", "Wake Forest"),
    ("University of Pittsburgh", "US", "Pitt"),
    ("University of Minnesota", "US", "UMN"),
    ("University of Colorado Boulder", "US", "CU Boulder"),
    ("University of Utah", "US", "UU"),
    ("Brigham Young University", "US", "BYU"),
    ("Stevens Institute of Technology", "US", "Stevens"),
    ("Rensselaer Polytechnic Institute", "US", "RPI"),
    ("Lehigh University", "US", "Lehigh"),
    ("University of Connecticut", "US", "UConn"),
    ("University of Iowa", "US", "UIowa"),
    ("Indiana University Bloomington", "US", "IU"),
    ("University of Georgia", "US", "UGA"),
    ("University of South Carolina", "US", "USC-SC"),
    ("Clemson University", "US", "Clemson"),
    ("Auburn University", "US", "Auburn"),
    ("University of Kansas", "US", "KU"),
    ("Kansas State University", "US", "K-State"),
    ("University of Kentucky", "US", "UK"),
    ("University of Tennessee", "US", "UT"),
    ("University of Missouri", "US", "Mizzou"),
    ("University of Oregon", "US", "UO"),
    ("Oregon State University", "US", "OSU-OR"),
    ("University of Nevada, Las Vegas", "US", "UNLV"),
    ("San Diego State University", "US", "SDSU"),
    ("San Jose State University", "US", "SJSU"),
    ("Cal Poly San Luis Obispo", "US", "Cal Poly"),
    ("Babson College", "US", "Babson"),
    ("Bentley University", "US", "Bentley"),
    ("Hult International Business School", "US", "Hult"),

    # ───────── United Kingdom ─────────
    ("University of Oxford", "GB", "Oxford"),
    ("University of Cambridge", "GB", "Cambridge"),
    ("Imperial College London", "GB", "Imperial"),
    ("University College London", "GB", "UCL"),
    ("London School of Economics", "GB", "LSE"),
    ("King's College London", "GB", "KCL"),
    ("University of Edinburgh", "GB", "UoE"),
    ("University of Manchester", "GB", "UoM"),
    ("University of Bristol", "GB", "Bristol"),
    ("University of Warwick", "GB", "Warwick"),
    ("University of Glasgow", "GB", "Glasgow"),
    ("University of Birmingham", "GB", "UoB"),
    ("University of Sheffield", "GB", "Sheffield"),
    ("University of Leeds", "GB", "Leeds"),
    ("University of Nottingham", "GB", "Nottingham"),
    ("University of Southampton", "GB", "Soton"),
    ("University of St Andrews", "GB", "St Andrews"),
    ("Durham University", "GB", "Durham"),
    ("Queen Mary University of London", "GB", "QMUL"),
    ("Lancaster University", "GB", "Lancaster"),
    ("University of Exeter", "GB", "Exeter"),
    ("University of York", "GB", "York"),
    ("Cardiff University", "GB", "Cardiff"),
    ("University of Liverpool", "GB", "Liverpool"),
    ("Newcastle University", "GB", "Newcastle"),

    # ───────── Canada ─────────
    ("University of Toronto", "CA", "UofT"),
    ("McGill University", "CA", "McGill"),
    ("University of British Columbia", "CA", "UBC"),
    ("University of Waterloo", "CA", "UWaterloo"),
    ("McMaster University", "CA", "McMaster"),
    ("University of Alberta", "CA", "UAlberta"),
    ("Queen's University", "CA", "Queen's"),
    ("Western University", "CA", "Western"),
    ("University of Montreal", "CA", "UdeM"),
    ("Simon Fraser University", "CA", "SFU"),
    ("University of Ottawa", "CA", "uOttawa"),
    ("Université Laval", "CA", "Laval"),
    ("Dalhousie University", "CA", "Dal"),
    ("University of Calgary", "CA", "UCalgary"),
    ("Concordia University", "CA", "Concordia"),
    ("York University", "CA", "York"),
    ("Ryerson University", "CA", "Ryerson"),

    # ───────── Australia / NZ ─────────
    ("University of Melbourne", "AU", "Melbourne"),
    ("Australian National University", "AU", "ANU"),
    ("University of Sydney", "AU", "USyd"),
    ("University of New South Wales", "AU", "UNSW"),
    ("University of Queensland", "AU", "UQ"),
    ("Monash University", "AU", "Monash"),
    ("University of Western Australia", "AU", "UWA"),
    ("University of Adelaide", "AU", "Adelaide"),
    ("University of Technology Sydney", "AU", "UTS"),
    ("University of Auckland", "NZ", "UoA"),
    ("University of Otago", "NZ", "Otago"),
    ("Victoria University of Wellington", "NZ", "VUW"),

    # ───────── China / Hong Kong / Taiwan ─────────
    ("Tsinghua University", "CN", "Tsinghua"),
    ("Peking University", "CN", "PKU"),
    ("Fudan University", "CN", "Fudan"),
    ("Shanghai Jiao Tong University", "CN", "SJTU"),
    ("Zhejiang University", "CN", "ZJU"),
    ("University of Science and Technology of China", "CN", "USTC"),
    ("Nanjing University", "CN", "Nanjing"),
    ("Sun Yat-sen University", "CN", "SYSU"),
    ("Wuhan University", "CN", "WHU"),
    ("University of Hong Kong", "HK", "HKU"),
    ("Hong Kong University of Science and Technology", "HK", "HKUST"),
    ("Chinese University of Hong Kong", "HK", "CUHK"),
    ("City University of Hong Kong", "HK", "CityU"),
    ("National Taiwan University", "TW", "NTU"),
    ("National Tsing Hua University", "TW", "NTHU"),
    ("National Cheng Kung University", "TW", "NCKU"),

    # ───────── Japan / Korea ─────────
    ("University of Tokyo", "JP", "Todai"),
    ("Kyoto University", "JP", "Kyodai"),
    ("Osaka University", "JP", "Handai"),
    ("Tokyo Institute of Technology", "JP", "Tokyo Tech"),
    ("Tohoku University", "JP", "Tohoku"),
    ("Nagoya University", "JP", "Nagoya"),
    ("Keio University", "JP", "Keio"),
    ("Waseda University", "JP", "Waseda"),
    ("Seoul National University", "KR", "SNU"),
    ("KAIST", "KR", "KAIST"),
    ("Yonsei University", "KR", "Yonsei"),
    ("Korea University", "KR", "KU"),
    ("POSTECH", "KR", "POSTECH"),
    ("Sungkyunkwan University", "KR", "SKKU"),

    # ───────── Singapore / India / SE Asia ─────────
    ("National University of Singapore", "SG", "NUS"),
    ("Nanyang Technological University", "SG", "NTU"),
    ("Singapore Management University", "SG", "SMU"),
    ("Indian Institute of Technology Bombay", "IN", "IIT Bombay"),
    ("Indian Institute of Technology Delhi", "IN", "IIT Delhi"),
    ("Indian Institute of Technology Madras", "IN", "IIT Madras"),
    ("Indian Institute of Technology Kanpur", "IN", "IIT Kanpur"),
    ("Indian Institute of Technology Kharagpur", "IN", "IIT KGP"),
    ("Indian Institute of Science", "IN", "IISc"),
    ("Indian Institute of Technology Roorkee", "IN", "IIT Roorkee"),
    ("Indian Institute of Technology Guwahati", "IN", "IIT G"),
    ("Delhi University", "IN", "DU"),
    ("BITS Pilani", "IN", "BITS"),
    ("University of Malaya", "MY", "UM"),
    ("Chulalongkorn University", "TH", "Chula"),
    ("Mahidol University", "TH", ""),
    ("University of the Philippines", "PH", "UP"),
    ("Ateneo de Manila University", "PH", "Ateneo"),
    ("De La Salle University", "PH", "DLSU"),
    ("University of Indonesia", "ID", "UI"),
    ("Institut Teknologi Bandung", "ID", "ITB"),
    ("Vietnam National University", "VN", "VNU"),

    # ───────── Europe (non-UK) ─────────
    ("ETH Zurich", "CH", "ETH"),
    ("EPFL", "CH", "EPFL"),
    ("University of Zurich", "CH", "UZH"),
    ("Technical University of Munich", "DE", "TUM"),
    ("Ludwig Maximilian University of Munich", "DE", "LMU"),
    ("Heidelberg University", "DE", ""),
    ("Humboldt University of Berlin", "DE", "HU Berlin"),
    ("Free University of Berlin", "DE", "FU Berlin"),
    ("RWTH Aachen University", "DE", "RWTH"),
    ("Delft University of Technology", "NL", "TU Delft"),
    ("University of Amsterdam", "NL", "UvA"),
    ("Utrecht University", "NL", ""),
    ("Leiden University", "NL", ""),
    ("Erasmus University Rotterdam", "NL", "EUR"),
    ("KU Leuven", "BE", "KUL"),
    ("Ghent University", "BE", "UGent"),
    ("Université catholique de Louvain", "BE", "UCLouvain"),
    ("Sorbonne University", "FR", "Sorbonne"),
    ("École Polytechnique", "FR", "X"),
    ("Sciences Po", "FR", ""),
    ("École Normale Supérieure", "FR", "ENS"),
    ("HEC Paris", "FR", "HEC"),
    ("INSEAD", "FR", "INSEAD"),
    ("PSL University", "FR", "PSL"),
    ("Université Paris-Saclay", "FR", ""),
    ("Bocconi University", "IT", "Bocconi"),
    ("University of Bologna", "IT", "UniBo"),
    ("Sapienza University of Rome", "IT", "Sapienza"),
    ("Politecnico di Milano", "IT", "Polimi"),
    ("University of Milan", "IT", "UniMi"),
    ("IE University", "ES", "IE"),
    ("IESE Business School", "ES", "IESE"),
    ("Universidad Autónoma de Madrid", "ES", "UAM"),
    ("Universidad Complutense de Madrid", "ES", "UCM"),
    ("Universidad de Barcelona", "ES", "UB"),
    ("Universidad Politécnica de Madrid", "ES", "UPM"),
    ("Universidad Pompeu Fabra", "ES", "UPF"),
    ("University of Lisbon", "PT", "UL"),
    ("NOVA University Lisbon", "PT", "NOVA"),
    ("University of Porto", "PT", "UP"),
    ("Trinity College Dublin", "IE", "TCD"),
    ("University College Dublin", "IE", "UCD"),
    ("Karolinska Institute", "SE", "KI"),
    ("KTH Royal Institute of Technology", "SE", "KTH"),
    ("Lund University", "SE", ""),
    ("Uppsala University", "SE", ""),
    ("University of Copenhagen", "DK", "KU"),
    ("Technical University of Denmark", "DK", "DTU"),
    ("University of Oslo", "NO", "UiO"),
    ("Norwegian University of Science and Technology", "NO", "NTNU"),
    ("University of Helsinki", "FI", ""),
    ("Aalto University", "FI", "Aalto"),
    ("University of Warsaw", "PL", "UW"),
    ("Jagiellonian University", "PL", ""),
    ("Charles University", "CZ", ""),
    ("Vienna University of Economics and Business", "AT", "WU"),
    ("University of Vienna", "AT", ""),
    ("Moscow State University", "RU", "MSU"),
    ("Higher School of Economics", "RU", "HSE"),

    # ───────── Latin America (non-Chile) ─────────
    ("Universidad Nacional Autónoma de México", "MX", "UNAM"),
    ("Tecnológico de Monterrey", "MX", "Tec"),
    ("Instituto Politécnico Nacional", "MX", "IPN"),
    ("Universidad Iberoamericana", "MX", "Ibero"),
    ("Universidad de las Américas Puebla", "MX", "UDLAP"),
    ("ITAM", "MX", "ITAM"),
    ("Universidad Anáhuac", "MX", "Anáhuac"),
    ("Universidad de Buenos Aires", "AR", "UBA"),
    ("Universidad Torcuato Di Tella", "AR", "UTDT"),
    ("Universidad de San Andrés", "AR", "UdeSA"),
    ("Universidad Austral", "AR", ""),
    ("Pontifícia Universidade Católica do Rio de Janeiro", "BR", "PUC-Rio"),
    ("Universidade de São Paulo", "BR", "USP"),
    ("Universidade Federal do Rio de Janeiro", "BR", "UFRJ"),
    ("Universidade Estadual de Campinas", "BR", "Unicamp"),
    ("Universidade Federal de Minas Gerais", "BR", "UFMG"),
    ("Fundação Getulio Vargas", "BR", "FGV"),
    ("Universidade de Brasília", "BR", "UnB"),
    ("Universidad de los Andes", "CO", "Uniandes"),
    ("Universidad Nacional de Colombia", "CO", "UNAL"),
    ("Pontificia Universidad Javeriana", "CO", "Javeriana"),
    ("Universidad del Rosario", "CO", ""),
    ("Universidad EAFIT", "CO", "EAFIT"),
    ("Universidad de Antioquia", "CO", "UdeA"),
    ("Pontificia Universidad Católica del Perú", "PE", "PUCP"),
    ("Universidad Nacional Mayor de San Marcos", "PE", "UNMSM"),
    ("Universidad del Pacífico", "PE", "UP"),
    ("Universidad de Lima", "PE", "ULima"),
    ("Universidad San Francisco de Quito", "EC", "USFQ"),
    ("Escuela Politécnica Nacional", "EC", "EPN"),
    ("Universidad de la República", "UY", "UdelaR"),
    ("Universidad ORT Uruguay", "UY", "ORT"),
    ("Universidad de Costa Rica", "CR", "UCR"),
    ("Instituto Tecnológico de Costa Rica", "CR", "TEC"),

    # ───────── Middle East / Africa ─────────
    ("Technion – Israel Institute of Technology", "IL", "Technion"),
    ("Tel Aviv University", "IL", "TAU"),
    ("Hebrew University of Jerusalem", "IL", "HUJI"),
    ("Weizmann Institute of Science", "IL", "Weizmann"),
    ("King Fahd University of Petroleum and Minerals", "SA", "KFUPM"),
        ("King Abdullah University of Science and Technology", "SA", "KAUST"),
    ("King Saud University", "SA", "KSU"),
    ("American University of Beirut", "LB", "AUB"),
    ("American University in Cairo", "EG", "AUC"),
    ("Cairo University", "EG", ""),
    ("Bogazici University", "TR", "BU"),
    ("Middle East Technical University", "TR", "METU"),
    ("Koç University", "TR", "Koç"),
    ("Bilkent University", "TR", "Bilkent"),
    ("University of Cape Town", "ZA", "UCT"),
    ("Stellenbosch University", "ZA", "SU"),
    ("University of the Witwatersrand", "ZA", "Wits"),
    ("University of Pretoria", "ZA", "UP"),
    ("University of Johannesburg", "ZA", "UJ"),
    ("University of Nairobi", "KE", ""),
    ("University of Cairo", "EG", ""),
    ("Makerere University", "UG", ""),
    ("University of Ghana", "GH", ""),
    ("University of Lagos", "NG", "UNILAG"),
    ("Covenant University", "NG", ""),
    # ── Expanded global batch ──
    ('Universidad de Buenos Aires', 'AR', 'UBA'),
    ('Universidad Nacional de La Plata', 'AR', 'UNLP'),
    ('Universidad Nacional de Córdoba', 'AR', 'UNC'),
    ('Universidad Nacional de Rosario', 'AR', 'UNR'),
    ('Universidad Tecnológica Nacional', 'AR', 'UTN'),
    ('Universidad Austral', 'AR', ''),
    ('Universidad de San Andrés', 'AR', 'UdeSA'),
    ('Universidad Torcuato Di Tella', 'AR', 'UTDT'),
    ('Universidad Nacional de Cuyo', 'AR', 'UNCuyo'),
    ('Universidad Nacional del Sur', 'AR', 'UNS'),
    ('Universidad Nacional del Litoral', 'AR', 'UNL'),
    ('Universidad Nacional de Tucumán', 'AR', 'UNT'),
    ('Universidad Nacional de Quilmes', 'AR', 'UNQ'),
    ('Universidad Nacional de San Martín', 'AR', 'UNSAM'),
    ('Universidad Católica Argentina', 'AR', 'UCA'),
    ('Universidad de Belgrano', 'AR', 'UB'),
    ('Universidad de Palermo', 'AR', 'UP'),
    ('Instituto Tecnológico de Buenos Aires', 'AR', 'ITBA'),
    ('Universidad de los Andes (Colombia)', 'CO', 'Uniandes'),
    ('Universidad Nacional de Colombia', 'CO', 'UNAL'),
    ('Pontificia Universidad Javeriana', 'CO', 'Javeriana'),
    ('Universidad del Rosario', 'CO', 'UR'),
    ('Universidad de Antioquia', 'CO', 'UdeA'),
    ('Universidad del Valle', 'CO', 'Univalle'),
    ('Universidad EAFIT', 'CO', 'EAFIT'),
    ('Universidad Externado de Colombia', 'CO', ''),
    ('Universidad Industrial de Santander', 'CO', 'UIS'),
    ('Universidad del Norte', 'CO', 'Uninorte'),
    ('Universidad ICESI', 'CO', 'ICESI'),
    ('Universidad de La Sabana', 'CO', ''),
    ('Universidad de Caldas', 'CO', ''),
    ('Universidad Pontificia Bolivariana', 'CO', 'UPB'),
    ('Universidad Militar Nueva Granada', 'CO', 'UMNG'),
    ('Pontificia Universidad Católica del Perú', 'PE', 'PUCP'),
    ('Universidad Nacional Mayor de San Marcos', 'PE', 'UNMSM'),
    ('Universidad Nacional de Ingeniería', 'PE', 'UNI'),
    ('Universidad del Pacífico', 'PE', 'UP'),
    ('Universidad de Lima', 'PE', 'ULima'),
    ('Universidad ESAN', 'PE', 'ESAN'),
    ('Universidad Peruana de Ciencias Aplicadas', 'PE', 'UPC'),
    ('Universidad San Ignacio de Loyola', 'PE', 'USIL'),
    ('Universidad Nacional Agraria La Molina', 'PE', 'UNALM'),
    ('Universidad Cayetano Heredia', 'PE', 'UPCH'),
    ('Universidad Nacional Autónoma de México', 'MX', 'UNAM'),
    ('Instituto Politécnico Nacional', 'MX', 'IPN'),
    ('Instituto Tecnológico y de Estudios Superiores de Monterrey', 'MX', 'Tec'),
    ('Universidad Autónoma Metropolitana', 'MX', 'UAM'),
    ('Universidad Iberoamericana', 'MX', 'Ibero'),
    ('Instituto Tecnológico Autónomo de México', 'MX', 'ITAM'),
    ('Universidad Panamericana', 'MX', 'UP'),
    ('Universidad Anáhuac', 'MX', 'Anáhuac'),
    ('Universidad de las Américas Puebla', 'MX', 'UDLAP'),
    ('Universidad La Salle', 'MX', 'ULSA'),
    ('Universidad de Guadalajara', 'MX', 'UdeG'),
    ('Universidad Autónoma de Nuevo León', 'MX', 'UANL'),
    ('Benemérita Universidad Autónoma de Puebla', 'MX', 'BUAP'),
    ('Universidad Autónoma del Estado de México', 'MX', 'UAEMex'),
    ('El Colegio de México', 'MX', 'COLMEX'),
    ('Universidade de São Paulo', 'BR', 'USP'),
    ('Universidade Estadual de Campinas', 'BR', 'Unicamp'),
    ('Universidade Federal do Rio de Janeiro', 'BR', 'UFRJ'),
    ('Universidade Federal de Minas Gerais', 'BR', 'UFMG'),
    ('Universidade Federal do Rio Grande do Sul', 'BR', 'UFRGS'),
    ('Universidade Estadual Paulista', 'BR', 'Unesp'),
    ('Pontifícia Universidade Católica do Rio de Janeiro', 'BR', 'PUC-Rio'),
    ('Pontifícia Universidade Católica de São Paulo', 'BR', 'PUC-SP'),
    ('Universidade Federal de Santa Catarina', 'BR', 'UFSC'),
    ('Universidade Federal do Paraná', 'BR', 'UFPR'),
    ('Universidade Federal de São Paulo', 'BR', 'Unifesp'),
    ('Instituto Tecnológico de Aeronáutica', 'BR', 'ITA'),
    ('Fundação Getulio Vargas', 'BR', 'FGV'),
    ('Universidade Federal de Pernambuco', 'BR', 'UFPE'),
    ('Universidade Federal da Bahia', 'BR', 'UFBA'),
    ('Universidad Complutense de Madrid', 'ES', 'UCM'),
    ('Universidad Autónoma de Madrid', 'ES', 'UAM'),
    ('Universidad Politécnica de Madrid', 'ES', 'UPM'),
    ('Universidad Carlos III de Madrid', 'ES', 'UC3M'),
    ('Universitat de Barcelona', 'ES', 'UB'),
    ('Universitat Autònoma de Barcelona', 'ES', 'UAB'),
    ('Universitat Politècnica de Catalunya', 'ES', 'UPC'),
    ('Universitat Pompeu Fabra', 'ES', 'UPF'),
    ('IE University', 'ES', 'IE'),
    ('IESE Business School', 'ES', 'IESE'),
    ('ESADE', 'ES', 'ESADE'),
    ('Universidad de Navarra', 'ES', 'UN'),
    ('Universidad de Valencia', 'ES', 'UV'),
    ('Universidad Politécnica de Valencia', 'ES', 'UPV'),
    ('Universidad de Granada', 'ES', 'UGR'),
    ('Universidad de Sevilla', 'ES', 'US'),
    ('Universidad de Salamanca', 'ES', 'USAL'),
    ('Universidad de Santiago de Compostela', 'ES', 'USC'),
    ('Universidad del País Vasco', 'ES', 'UPV/EHU'),
    ('Universidad de Zaragoza', 'ES', 'Unizar'),
    ('Universidad Pontificia Comillas', 'ES', 'Comillas'),
    ('Universidad de Deusto', 'ES', 'Deusto'),
    ('Technische Universität München', 'DE', 'TUM'),
    ('Ludwig-Maximilians-Universität München', 'DE', 'LMU'),
    ('Ruprecht-Karls-Universität Heidelberg', 'DE', 'Heidelberg'),
    ('Humboldt-Universität zu Berlin', 'DE', 'HU Berlin'),
    ('Freie Universität Berlin', 'DE', 'FU Berlin'),
    ('RWTH Aachen University', 'DE', 'RWTH'),
    ('Karlsruher Institut für Technologie', 'DE', 'KIT'),
    ('Universität Hamburg', 'DE', 'UHH'),
    ('Universität Bonn', 'DE', 'Bonn'),
    ('Universität Tübingen', 'DE', 'Tübingen'),
    ('Universität Köln', 'DE', 'Köln'),
    ('Goethe-Universität Frankfurt', 'DE', 'Goethe'),
    ('Technische Universität Berlin', 'DE', 'TU Berlin'),
    ('Universität Stuttgart', 'DE', 'Stuttgart'),
    ('Universität Göttingen', 'DE', 'Göttingen'),
    ('Sorbonne Université', 'FR', 'Sorbonne'),
    ('Université Paris-Saclay', 'FR', 'Paris-Saclay'),
    ('Université PSL', 'FR', 'PSL'),
    ('École Polytechnique', 'FR', 'X'),
    ('École Normale Supérieure', 'FR', 'ENS'),
    ('Sciences Po', 'FR', ''),
    ('HEC Paris', 'FR', 'HEC'),
    ('INSEAD', 'FR', ''),
    ('ESSEC Business School', 'FR', 'ESSEC'),
    ('ESCP Business School', 'FR', 'ESCP'),
    ('Université de Paris Cité', 'FR', ''),
    ('Université Grenoble Alpes', 'FR', 'UGA'),
    ('Université Lyon 1', 'FR', 'Lyon 1'),
    ('Université Aix-Marseille', 'FR', 'AMU'),
    ('Université de Strasbourg', 'FR', 'Unistra'),
    ('Sorbonne Nouvelle', 'FR', ''),
    ('Università di Bologna', 'IT', 'UniBO'),
    ('Sapienza Università di Roma', 'IT', 'Sapienza'),
    ('Politecnico di Milano', 'IT', 'PoliMi'),
    ('Università degli Studi di Milano', 'IT', 'UniMi'),
    ('Università di Padova', 'IT', 'UniPD'),
    ('Università Bocconi', 'IT', 'Bocconi'),
    ('Università Cattolica del Sacro Cuore', 'IT', 'UCSC'),
    ('Politecnico di Torino', 'IT', 'PoliTO'),
    ('Università di Pisa', 'IT', 'UniPi'),
    ('Scuola Normale Superiore', 'IT', 'SNS'),
    ('Università di Napoli Federico II', 'IT', 'UniNa'),
    ('University of Sussex', 'GB', 'Sussex'),
    ('University of East Anglia', 'GB', 'UEA'),
    ('University of Reading', 'GB', 'Reading'),
    ('University of Surrey', 'GB', 'Surrey'),
    ('University of Strathclyde', 'GB', 'Strathclyde'),
    ('University of Aberdeen', 'GB', ''),
    ('University of Dundee', 'GB', ''),
    ('University of Liverpool', 'GB', ''),
    ('Cardiff University', 'GB', ''),
    ("Queen's University Belfast", 'GB', 'QUB'),
    ('Imperial College Business School', 'GB', ''),
    ('London Business School', 'GB', 'LBS'),
    ('SOAS University of London', 'GB', 'SOAS'),
    ('Goldsmiths, University of London', 'GB', ''),
    ('Vrije Universiteit Amsterdam', 'NL', 'VU'),
    ('Erasmus University Rotterdam', 'NL', 'EUR'),
    ('Leiden University', 'NL', ''),
    ('University of Groningen', 'NL', ''),
    ('Radboud University', 'NL', ''),
    ('Wageningen University & Research', 'NL', 'WUR'),
    ('Maastricht University', 'NL', 'UM'),
    ('Keio University', 'JP', 'Keio'),
    ('Waseda University', 'JP', 'Waseda'),
    ('Nagoya University', 'JP', ''),
    ('Hokkaido University', 'JP', ''),
    ('Tohoku University', 'JP', ''),
    ('Kyushu University', 'JP', ''),
    ('Nanjing University', 'CN', ''),
    ("Xi'an Jiaotong University", 'CN', 'XJTU'),
    ('Wuhan University', 'CN', ''),
    ('Harbin Institute of Technology', 'CN', 'HIT'),
    ('Beijing Normal University', 'CN', 'BNU'),
    ('Sun Yat-sen University', 'CN', ''),
    ('Central University of Finance and Economics', 'CN', 'CUFE'),
    ('Indian Institute of Technology Kanpur', 'IN', 'IIT Kanpur'),
    ('Indian Institute of Technology Kharagpur', 'IN', 'IIT Kharagpur'),
    ('Indian Institute of Technology Roorkee', 'IN', 'IIT Roorkee'),
    ('Indian Institute of Technology Guwahati', 'IN', 'IIT Guwahati'),
    ('Indian Institute of Technology Hyderabad', 'IN', 'IIT Hyderabad'),
    ('Indian School of Business', 'IN', 'ISB'),
    ('University of Delhi', 'IN', 'DU'),
    ('Jawaharlal Nehru University', 'IN', 'JNU'),
    ('BITS Pilani', 'IN', 'BITS'),
    ('Jamia Millia Islamia', 'IN', 'JMI'),
    ('Banaras Hindu University', 'IN', 'BHU'),
    ('Manipal Academy of Higher Education', 'IN', 'MAHE'),
    ('University of Victoria', 'CA', 'UVic'),
    ('Carleton University', 'CA', ''),
    ('Simon Fraser University', 'CA', 'SFU'),
    ('Concordia University', 'CA', 'Concordia'),
    ('Australian National University', 'AU', 'ANU'),
    ('University of Queensland', 'AU', 'UQ'),
    ('University of Adelaide', 'AU', 'Adelaide'),
    ('Macquarie University', 'AU', 'MQ'),
    ('University of Technology Sydney', 'AU', 'UTS'),
    ('Queensland University of Technology', 'AU', 'QUT'),
    ('Universidade de Lisboa', 'PT', 'UL'),
    ('Universidade do Porto', 'PT', 'UP'),
    ('Universidade Nova de Lisboa', 'PT', 'UNL'),
    ('Universidade de Coimbra', 'PT', 'UC'),
    ('Universidade do Minho', 'PT', ''),
    ('ISCTE – Instituto Universitário de Lisboa', 'PT', 'ISCTE'),
    ('École Polytechnique Fédérale de Lausanne', 'CH', 'EPFL'),
    ('ETH Zürich', 'CH', 'ETH'),
    ('University of Zurich', 'CH', 'UZH'),
    ('University of Geneva', 'CH', 'UNIGE'),
    ('University of Lausanne', 'CH', 'UNIL'),
    ('University of St. Gallen', 'CH', 'HSG'),
    ('KU Leuven', 'BE', 'KUL'),
    ('Ghent University', 'BE', 'UGent'),
    ('Université libre de Bruxelles', 'BE', 'ULB'),
    ('Université catholique de Louvain', 'BE', 'UCLouvain'),
    ('Trinity College Dublin', 'IE', 'TCD'),
    ('University College Dublin', 'IE', 'UCD'),
    ('Dublin City University', 'IE', 'DCU'),
    ('University of Galway', 'IE', 'UG'),
    ('Lund University', 'SE', ''),
    ('Uppsala University', 'SE', ''),
    ('Stockholm University', 'SE', ''),
    ('KTH Royal Institute of Technology', 'SE', 'KTH'),
    ('Chalmers University of Technology', 'SE', 'Chalmers'),
    ('University of Copenhagen', 'DK', 'KU'),
    ('Technical University of Denmark', 'DK', 'DTU'),
    ('Aarhus University', 'DK', ''),
    ('University of Oslo', 'NO', 'UiO'),
    ('Norwegian University of Science and Technology', 'NO', 'NTNU'),
    ('University of Helsinki', 'FI', ''),
    ('Aalto University', 'FI', 'Aalto'),
    ('Universidad Central de Venezuela', 'VE', 'UCV'),
    ('Universidad Simón Bolívar', 'VE', 'USB'),
    ('Universidad Católica Andrés Bello', 'VE', 'UCAB'),
    ('Universidad de la República', 'UY', 'UdelaR'),
    ('Universidad ORT Uruguay', 'UY', 'ORT'),
    ('Universidad Mayor de San Andrés', 'BO', 'UMSA'),
    ('Universidad Católica Boliviana', 'BO', 'UCB'),
    ('Universidad Privada de Santa Cruz de la Sierra', 'BO', 'UPSA'),
    ('Yonsei University', 'KR', 'Yonsei'),
    ('Korea University', 'KR', 'KU'),
    ('Pohang University of Science and Technology', 'KR', 'POSTECH'),
    ('Sungkyunkwan University', 'KR', 'SKKU'),
    ('Hanyang University', 'KR', 'Hanyang'),
    ('Nanyang Technological University', 'SG', 'NTU'),
    ('National University of Singapore', 'SG', 'NUS'),
    ('Singapore Management University', 'SG', 'SMU'),
    ('Chinese University of Hong Kong', 'HK', 'CUHK'),
    ('Hong Kong University of Science and Technology', 'HK', 'HKUST'),
    ('Hong Kong Polytechnic University', 'HK', 'PolyU'),
    ('National Taiwan University', 'TW', 'NTU'),
    ('National Tsing Hua University', 'TW', 'NTHU'),
    ('National Chiao Tung University', 'TW', 'NCTU'),
    ('Lomonosov Moscow State University', 'RU', 'MSU'),
    ('Saint Petersburg State University', 'RU', 'SPbSU'),
    ('Higher School of Economics', 'RU', 'HSE'),
    ('Moscow Institute of Physics and Technology', 'RU', 'MIPT'),
    ('University of Warsaw', 'PL', 'UW'),
    ('Jagiellonian University', 'PL', ''),
    ('Charles University', 'CZ', ''),
    ('University of Vienna', 'AT', ''),
    ('Vienna University of Economics and Business', 'AT', 'WU'),

]


# ─────────────────────────────────────────────────────────────────────
#  GLOBAL MAJORS  — university-agnostic, available everywhere.
#  Loaded with university_id = NULL.  Users can also create custom
#  majors scoped to their university.
# ─────────────────────────────────────────────────────────────────────
GLOBAL_MAJORS: list[str] = [
    # ── Engineering ──
    "Computer Science",
    "Software Engineering",
    "Computer Engineering",
    "Electrical Engineering",
    "Electronic Engineering",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Civil Engineering",
    "Industrial Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Aeronautical Engineering",
    "Environmental Engineering",
    "Materials Engineering",
    "Mining Engineering",
    "Petroleum Engineering",
    "Nuclear Engineering",
    "Structural Engineering",
    "Geological Engineering",
    "Agricultural Engineering",
    "Food Engineering",
    "Marine Engineering",
    "Naval Architecture",
    "Robotics Engineering",
    "Engineering Physics",
    "Engineering Management",

    # ── Business & Economics ──
    "Business Administration",
    "Management",
    "Accounting",
    "Finance",
    "Marketing",
    "International Business",
    "Entrepreneurship",
    "Human Resources",
    "Supply Chain Management",
    "Operations Management",
    "Economics",
    "Econometrics",
    "Actuarial Science",
    "Real Estate",
    "Hospitality Management",
    "Tourism Management",

    # ── Computing & Data ──
    "Information Technology",
    "Information Systems",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Cybersecurity",
    "Network Engineering",
    "Cloud Computing",
    "Game Development",
    "Human-Computer Interaction",
    "Computational Biology",
    "Bioinformatics",

    # ── Natural Sciences ──
    "Mathematics",
    "Applied Mathematics",
    "Statistics",
    "Physics",
    "Astrophysics",
    "Astronomy",
    "Chemistry",
    "Biochemistry",
    "Biology",
    "Molecular Biology",
    "Microbiology",
    "Genetics",
    "Neuroscience",
    "Ecology",
    "Marine Biology",
    "Zoology",
    "Botany",
    "Geology",
    "Geophysics",
    "Meteorology",
    "Oceanography",
    "Environmental Science",

    # ── Health Sciences ──
    "Medicine",
    "Dentistry",
    "Veterinary Medicine",
    "Pharmacy",
    "Nursing",
    "Midwifery",
    "Public Health",
    "Nutrition and Dietetics",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech and Language Therapy",
    "Optometry",
    "Audiology",
    "Kinesiology",
    "Sports Science",
    "Health Sciences",
    "Medical Technology",

    # ── Social Sciences ──
    "Psychology",
    "Sociology",
    "Anthropology",
    "Political Science",
    "International Relations",
    "Public Administration",
    "Public Policy",
    "Criminology",
    "Social Work",
    "Geography",
    "Demography",
    "Urban Studies",
    "Gender Studies",

    # ── Humanities ──
    "Philosophy",
    "History",
    "Theology",
    "Religious Studies",
    "Classics",
    "Archaeology",
    "Linguistics",
    "Literature",
    "English Literature",
    "Comparative Literature",
    "Modern Languages",
    "Translation and Interpretation",

    # ── Arts ──
    "Fine Arts",
    "Visual Arts",
    "Graphic Design",
    "Industrial Design",
    "Interior Design",
    "Fashion Design",
    "Animation",
    "Film and Television",
    "Photography",
    "Music",
    "Music Performance",
    "Music Production",
    "Theater",
    "Dance",
    "Performing Arts",
    "Architecture",
    "Landscape Architecture",
    "Urban Planning",

    # ── Communications & Media ──
    "Journalism",
    "Communications",
    "Media Studies",
    "Public Relations",
    "Advertising",
    "Digital Media",
    "Broadcasting",
    "Audiovisual Production",

    # ── Law ──
    "Law",
    "Legal Studies",
    "Criminal Justice",
    "International Law",

    # ── Education ──
    "Education",
    "Early Childhood Education",
    "Primary Education",
    "Secondary Education",
    "Special Education",
    "Educational Psychology",
    "Curriculum and Instruction",

    # ── Agriculture & Environment ──
    "Agriculture",
    "Agronomy",
    "Animal Science",
    "Forestry",
    "Horticulture",
    "Aquaculture",
    "Sustainable Development",
    "Environmental Studies",

    # ── Misc / Pre-professional ──
    "Liberal Arts",
    "Interdisciplinary Studies",
    "Cognitive Science",
    "Behavioral Science",
    "Pre-Med",
    "Pre-Law",
    "Undecided",

    # ── Expanded batch ──
    'Automotive Engineering',
    'Systems Engineering',
    'Manufacturing Engineering',
    'Ocean Engineering',
    'Transportation Engineering',
    'Geotechnical Engineering',
    'Water Resources Engineering',
    'Photonics Engineering',
    'Sustainable Energy Engineering',
    'Renewable Energy Engineering',
    'Automation Engineering',
    'Instrumentation Engineering',
    'Game Design',
    'DevOps Engineering',
    'Quantum Computing',
    'Blockchain Engineering',
    'Development Studies',
    'Speech-Language Pathology',
    'Radiologic Technology',
    'Medical Laboratory Science',
    'Biotechnology',
    'Biomedical Sciences',
    'Exercise Science',
    'Earth Sciences',
    'Atmospheric Sciences',
    'Creative Writing',
    'Art History',
    'Museum Studies',
    'Musicology',
    'Composition',
    'Performance',
    'Music Theory',
    'Film Studies',
    'Film Production',
    'Television Production',
    'Product Design',
    'Sculpture',
    'Illustration',
    'Communication Studies',
    'Educational Leadership',
    'English Language Teaching',
    'Mathematics Education',
    'Spanish Language and Literature',
    'French Language and Literature',
    'German Language and Literature',
    'Italian Language and Literature',
    'Chinese Language and Literature',
    'Japanese Studies',
    'Korean Studies',
    'Arabic Studies',
    'Hebrew Studies',
    'Russian Studies',
    'Latin American Studies',
    'Political Economy',
    'Environmental Policy',
    'Energy Policy',
    'Food Science',
    'Culinary Arts',
    'Hospitality and Tourism',
    'Aviation',
    'Maritime Studies',
    'Military Science',
    'Intelligence and Security Studies',

]


# ─────────────────────────────────────────────────────────────────────
#  SPANISH-LANGUAGE MAJOR NAMES (Latin America / Spain)
#  Added as separate rows so Spanish-typing students can find them.
#  Keep the most common ones — ranges across Chile, Mexico, Argentina,
#  Spain, Colombia, Peru.
# ─────────────────────────────────────────────────────────────────────
GLOBAL_MAJORS_ES: list[str] = [
    # Ingenierías
    "Ingeniería Civil",
    "Ingeniería Civil Industrial",
    "Ingeniería Civil Eléctrica",
    "Ingeniería Civil Mecánica",
    "Ingeniería Civil Química",
    "Ingeniería Civil Estructural",
    "Ingeniería Civil Hidráulica",
    "Ingeniería Civil de Minas",
    "Ingeniería Civil de Computación",
    "Ingeniería Civil Biomédica",
    "Ingeniería Comercial",
    "Ingeniería en Informática",
    "Ingeniería en Computación",
    "Ingeniería de Software",
    "Ingeniería en Ciencia de Datos",
    "Ingeniería Mecánica",
    "Ingeniería Eléctrica",
    "Ingeniería Electrónica",
    "Ingeniería Mecatrónica",
    "Ingeniería Química",
    "Ingeniería Industrial",
    "Ingeniería de Sistemas",
    "Ingeniería en Telecomunicaciones",
    "Ingeniería Ambiental",
    "Ingeniería en Construcción",
    "Ingeniería Aeroespacial",
    "Ingeniería Forestal",
    "Ingeniería Agronómica",
    "Ingeniería en Alimentos",
    # Negocios
    "Administración de Empresas",
    "Contabilidad y Auditoría",
    "Auditoría",
    "Contabilidad",
    "Marketing",
    "Comercio Internacional",
    "Negocios Internacionales",
    # Ciencias
    "Matemáticas",
    "Estadística",
    "Física",
    "Química",
    "Biología",
    "Bioquímica",
    "Geología",
    "Astronomía",
    # Salud
    "Medicina",
    "Odontología",
    "Enfermería",
    "Kinesiología",
    "Nutrición y Dietética",
    "Tecnología Médica",
    "Obstetricia",
    "Fonoaudiología",
    "Terapia Ocupacional",
    "Medicina Veterinaria",
    "Química y Farmacia",
    "Farmacia",
    # Sociales
    "Psicología",
    "Sociología",
    "Antropología",
    "Trabajo Social",
    "Ciencia Política",
    "Relaciones Internacionales",
    "Periodismo",
    "Comunicación Social",
    "Publicidad",
    # Humanidades
    "Filosofía",
    "Historia",
    "Teología",
    "Letras",
    "Lingüística",
    "Literatura",
    "Pedagogía",
    "Educación",
    "Educación Parvularia",
    "Educación Básica",
    # Arte y diseño
    "Arquitectura",
    "Diseño",
    "Diseño Gráfico",
    "Diseño Industrial",
    "Diseño de Vestuario",
    "Bellas Artes",
    "Artes Visuales",
    "Música",
    "Cine",
    "Teatro",
    # Derecho
    "Derecho",
    # Otros
    "Agronomía",
    "Veterinaria",
    "Geografía",
    "Turismo",
    "Hotelería",

    # ── Expanded batch ──
    'Ingeniería Civil Informática',
    'Ingeniería Civil Metalúrgica',
    'Ingeniería Civil Ambiental',
    'Ingeniería en Biotecnología',
    'Ingeniería en Energías Renovables',
    'Ingeniería en Automatización y Robótica',
    'Ingeniería Agrícola',
    'Ingeniería en Agronegocios',
    'Ingeniería en Sonido',
    'Ingeniería Acústica',
    'Biotecnología',
    'Obstetricia y Puericultura',
    'Economía',
    'Recursos Humanos',
    'Ingeniería en Gestión',
    'Finanzas',
    'Emprendimiento',
    'Administración Pública',
    'Hotelería y Turismo',
    'Gastronomía',
    'Pedagogía en Castellano',
    'Pedagogía en Matemáticas',
    'Pedagogía en Historia y Geografía',
    'Pedagogía Básica',
    'Pedagogía en Educación Parvularia',
    'Pedagogía en Educación Diferencial',
    'Pedagogía en Educación Física',
    'Pedagogía en Inglés',
    'Diseño de Productos',
    'Diseño de Interiores',
    'Artes Plásticas',
    'Interpretación Musical',
    'Composición Musical',
    'Dirección Orquestal',
    'Canto',
    'Actuación',
    'Danza',
    'Animación Digital',
    'Fotografía',
    'Relaciones Públicas',
    'Enología',
    'Medicina Integrativa',
    'Quiropráctica',
    'Ciencias de la Actividad Física',
    'Ciencias del Deporte',
    'Astronomía y Astrofísica',
    'Oceanografía',
    'Acuicultura',
    'Ingeniería Pesquera',
    'Técnico en Programación',
    'Análisis de Sistemas',
    'Ciencia de Datos',
    'Inteligencia Artificial',
    'Ciberseguridad',

]


# ─────────────────────────────────────────────────────────────────────
#  PER-UNIVERSITY CARRERAS (majors)
#  Maps a university name (exact match against UNIVERSITIES seed) to its
#  real programme catalogue. When a student picks a university on the
#  onboarding modal, these appear FIRST in the major search so they can
#  browse the actual options offered at their school.
#
#  Coverage: major Chilean universities (where most of our users are).
#  Missing universities fall back to GLOBAL_MAJORS + GLOBAL_MAJORS_ES.
# ─────────────────────────────────────────────────────────────────────

# Core carreras that almost every major Chilean university offers —
# we'll blend this into each university's list so users always find
# the common ones even if we missed a specific programme.
_CHILE_COMMON = [
    "Administración de Empresas",
    "Arquitectura",
    "Contabilidad y Auditoría",
    "Derecho",
    "Diseño",
    "Enfermería",
    "Ingeniería Civil",
    "Ingeniería Civil Industrial",
    "Ingeniería Civil Informática",
    "Ingeniería Comercial",
    "Ingeniería en Informática",
    "Kinesiología",
    "Medicina",
    "Nutrición y Dietética",
    "Obstetricia",
    "Odontología",
    "Pedagogía en Educación Básica",
    "Pedagogía en Educación de Párvulos",
    "Periodismo",
    "Psicología",
    "Publicidad",
    "Sociología",
    "Tecnología Médica",
    "Trabajo Social",
]

# Universities whose major lists are authoritative — the seeder will
# replace the university's majors with EXACTLY the list below (no common
# Chilean carreras merged, and stale rows are purged). Add a university
# here only once its list has been verified against the official source.
AUTHORITATIVE_UNIVERSITIES: set[str] = {
    "Pontificia Universidad Católica de Chile",
    "Universidad de Chile",
    "Universidad Técnica Federico Santa María",
    "Universidad Adolfo Ibáñez",
    "Universidad del Desarrollo",
    "Universidad Andrés Bello",
    "Universidad de los Andes",
}

UNIVERSITY_MAJORS: dict[str, list[str]] = {
    # ─── Pontificia Universidad Católica de Chile (PUC) ───
    # Authoritative carreras list as provided by the user.
    "Pontificia Universidad Católica de Chile": [
        "Actuación",
        "Administración Pública",
        "Agronomía",
        "Agronomía e Ingeniería Forestal",
        "Antropología",
        "Antropología-Arqueología",
        "Arqueología",
        "Arquitectura",
        "Arte",
        "Astronomía",
        "Bachillerato Inicia en Ciencias Naturales y Matemática",
        "Bachillerato Inicia en Ciencias Sociales",
        "Biología",
        "Biología Marina",
        "Bioquímica",
        "Ciencia Política",
        "College Artes y Humanidades",
        "College Ciencias Naturales y Matemáticas",
        "College Ciencias Sociales",
        "Construcción Civil",
        "Derecho",
        "Dirección Audiovisual",
        "Diseño",
        "Enfermería",
        "Estadística",
        "Estética",
        "Filosofía",
        "Física",
        "Fonoaudiología",
        "Geografía",
        "Historia",
        "Ingeniería Plan Comun",
        "Ingeniería Comercial",
        "Ingeniería en Recursos Naturales",
        "Ingeniería Forestal",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil Computación",
        "Ingeniería Civil Eléctrica",
        "Ingeniería Civil Mecánica",
        "Ingeniería Civil Matemática",
        "Ingeniería Civil Química",
        "Ingeniería Civil Ambiental",
        "Ingeniería Civil Transporte",
        "Ingeniería Civil Hidráulica",
        "Interpretación Musical",
        "Kinesiología",
        "Letras Hispánicas",
        "Letras Inglesas",
        "Licenciatura en Ingeniería en Ciencia de Datos",
        "Licenciatura en Ingeniería en Ciencia de la Computación",
        "Matemática",
        "Medicina",
        "Medicina Veterinaria",
        "Música",
        "Nutrición y Dietética",
        "Odontología",
        "Pedagogía en Educación Especial",
        "Pedagogía en Educación Física y Salud para Educación Básica y Media",
        "Pedagogía en Educación General Básica",
        "Pedagogía en Educación Media",
        "Pedagogía en Educación Media en Biología y Ciencias Naturales",
        "Pedagogía en Educación Media en Física",
        "Pedagogía en Educación Media en Matemática",
        "Pedagogía en Educación Media en Química",
        "Pedagogía en Educación Parvularia",
        "Pedagogía en Inglés para Educación Básica y Media",
        "Pedagogía en Religión Católica",
        "Periodismo",
        "Planificación Urbana",
        "Programa de Pedagogía para Profesionales",
        "Psicología",
        "Publicidad",
        "Química",
        "Química y Farmacia",
        "Sociología",
        "Teología",
        "Terapia Ocupacional",
    ],
    # ─── Universidad de Chile ───
    # Authoritative carreras list as provided by the user.
    "Universidad de Chile": [
        "Arquitectura",
        "Diseño",
        "Geografía",
        "Actuación Teatral",
        "Artes Visuales",
        "Composición Musical",
        "Danza",
        "Diseño Teatral",
        "Ingeniería en Sonido",
        "Interpretación Musical",
        "Teoría de la Música",
        "Teoría e Historia del Arte",
        "Biología con mención en Medio Ambiente",
        "Ingeniería en Biotecnología Molecular",
        "Licenciatura en Ciencias con mención en Biología",
        "Licenciatura en Ciencias con mención en Física",
        "Licenciatura en Ciencias con mención en Matemática",
        "Licenciatura en Ciencias con mención en Química",
        "Química Ambiental",
        "Pedagogía en Educación Media en Biología y Química",
        "Pedagogía en Educación Media en Matemáticas y Física",
        "Ingeniería Agronómica",
        "Ingeniería en Recursos Naturales Renovables",
        "Astronomía",
        "Física",
        "Geofísica",
        "Geología",
        "Ingeniería Civil",
        "Ingeniería Civil Eléctrica",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil Matemática",
        "Ingeniería Civil Mecánica",
        "Ingeniería Civil Química",
        "Ingeniería Civil de Minas",
        "Ingeniería Civil en Biotecnología",
        "Ingeniería Civil en Computación",
        "Ingeniería Forestal",
        "Ingeniería en Recursos Hídricos",
        "Bioquímica",
        "Ingeniería en Alimentos",
        "Química",
        "Química y Farmacia",
        "Antropología-Arqueología",
        "Pedagogía en Educación Especial",
        "Pedagogía en Educación Física",
        "Pedagogía en Educación Parvularia",
        "Psicología",
        "Sociología",
        "Trabajo Social",
        "Medicina Veterinaria",
        "Cine y Televisión",
        "Periodismo",
        "Derecho",
        "Contador Auditor",
        "Ingeniería Comercial",
        "Ingeniería en Información y Control de Gestión",
        "Estudios Internacionales",
        "Licenciatura en Filosofía",
        "Licenciatura en Historia",
        "Licenciatura en Lingüística y Literatura",
        "Licenciatura en Lingüística y Literatura Inglesas",
        "Pedagogía de Educación Media en Asignaturas Científico-Humanistas",
        "Pedagogía en Educación Básica",
        "Administración Pública",
        "Ciencia Política",
        "Enfermería",
        "Fonoaudiología",
        "Kinesiología",
        "Medicina",
        "Nutrición y Dietética",
        "Obstetricia y Puericultura",
        "Tecnología Médica",
        "Terapia Ocupacional",
        "Odontología",
        "Programa Académico de Bachillerato",
    ],
    # ─── Universidad Técnica Federico Santa María (USM) ───
    # Authoritative carreras list as provided by the user.
    "Universidad Técnica Federico Santa María": [
        "Arquitectura",
        "Construcción Civil",
        "Ingeniería Comercial",
        "Ingeniería Civil",
        "Ingeniería Civil Ambiental",
        "Ingeniería Civil de Minas",
        "Ingeniería Civil Eléctrica",
        "Ingeniería Civil Electrónica",
        "Ingeniería Civil Informática",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil Matemática",
        "Ingeniería Civil Mecánica",
        "Ingeniería Civil Química",
        "Ingeniería Civil Telemática",
        "Ingeniería en Aviación Comercial",
        "Ingeniería en Biotecnología",
        "Ingeniería en Diseño de Productos",
        "Ingeniería en Fabricación y Diseño Industrial",
        "Ingeniería en Informática",
        "Ingeniería en Mantenimiento Industrial",
        "Ingeniería en Prevención de Riesgos Laborales y Ambientales",
        "Ingeniería en Recursos Naturales",
        "Ingeniería en Transporte Marítimo y Puertos",
        "Licenciatura en Astrofísica",
        "Licenciatura en Física",
        "Licenciatura en Ciencias mención Química",
        "Química",
    ],
    # ─── Universidad de Santiago (USACH) ───
    "Universidad de Santiago de Chile": [
        "Administración Pública", "Arquitectura", "Bachillerato en Ciencias",
        "Bioquímica", "Contador Público y Auditor", "Derecho",
        "Diseño Industrial", "Educación General Básica",
        "Enfermería", "Estudios Internacionales", "Filosofía",
        "Física Aplicada", "Fonoaudiología", "Geografía",
        "Ingeniería Civil", "Ingeniería Civil en Ambiente",
        "Ingeniería Civil en Biotecnología", "Ingeniería Civil en Computación",
        "Ingeniería Civil Eléctrica", "Ingeniería Civil en Electrónica",
        "Ingeniería Civil en Geografía", "Ingeniería Civil Industrial",
        "Ingeniería Civil en Informática", "Ingeniería Civil en Mecánica",
        "Ingeniería Civil Metalúrgica", "Ingeniería Civil en Minas",
        "Ingeniería Civil en Obras Civiles", "Ingeniería Civil Química",
        "Ingeniería Comercial", "Ingeniería de Alimentos",
        "Ingeniería de Ejecución en Computación e Informática",
        "Ingeniería de Ejecución en Electricidad", "Ingeniería de Ejecución en Electrónica",
        "Ingeniería de Ejecución Industrial", "Ingeniería de Ejecución Mecánica",
        "Ingeniería de Ejecución en Metalurgia", "Ingeniería de Ejecución Química",
        "Ingeniería en Agronegocios", "Ingeniería en Biotecnología",
        "Ingeniería en Matemática", "Kinesiología", "Licenciatura en Ciencia de la Computación",
        "Licenciatura en Educación en Castellano", "Licenciatura en Educación en Matemática",
        "Licenciatura en Historia", "Licenciatura en Inglés",
        "Licenciatura en Lingüística", "Medicina", "Obstetricia y Puericultura",
        "Pedagogía en Biología y Ciencias Naturales", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Física", "Pedagogía en Educación Parvularia",
        "Pedagogía en Filosofía", "Pedagogía en Física y Matemática",
        "Pedagogía en Historia y Ciencias Sociales", "Pedagogía en Química y Biología",
        "Periodismo", "Psicología", "Publicidad", "Química",
        "Química y Farmacia", "Terapia Ocupacional", "Trabajo Social",
    ],
    # ─── Universidad del Desarrollo (UDD) ───
    # Authoritative carreras list as provided by the user.
    "Universidad del Desarrollo": [
        "Arquitectura",
        "Bachillerato en Derecho, Ciencias Sociales y Humanidades",
        "Bachillerato en Diseño",
        "Bachillerato en Enfermería",
        "Bachillerato en Ingeniería Comercial",
        "Bachillerato en Psicología",
        "Ciencia Política y Políticas Públicas",
        "Cine y Comunicación Audiovisual",
        "Derecho",
        "Diseño",
        "Enfermería",
        "Geología",
        "Global Business Administration",
        "Ingeniería Civil en BioMedicina",
        "Ingeniería Civil en Informática e Innovación Tecnológica",
        "Ingeniería Civil en Informática e Inteligencia Artificial",
        "Ingeniería Civil en Minería",
        "Ingeniería Civil en Obras Civiles",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil (Plan Común)",
        "Ingeniería Comercial",
        "Kinesiología",
        "Medicina",
        "Negocios y Ciencia de Datos",
        "Nutrición y Dietética",
        "Obstetricia",
        "Odontología",
        "Pedagogía en Educación Básica",
        "Pedagogía en Educación de Párvulos",
        "Periodismo y Comunicación",
        "Psicología",
        "Publicidad y Marketing",
        "Química y Farmacia",
        "Tecnología Médica",
        "Terapia Ocupacional",
    ],
    # ─── Universidad Adolfo Ibáñez (UAI) ───
    # Authoritative carreras list as provided by the user.
    "Universidad Adolfo Ibáñez": [
        "Arquitectura",
        "Derecho",
        "Ingeniería Comercial",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil en Bioingeniería",
        "Ingeniería Civil en Computación",
        "Ingeniería en Diseño",
        "Psicología",
        "Periodismo",
        "Licenciatura en Historia",
        "Licenciatura en Literatura",
    ],
    # ─── Universidad Diego Portales (UDP) ───
    "Universidad Diego Portales": [
        "Arquitectura", "Cine", "Derecho", "Diseño", "Enfermería",
        "Ingeniería Civil en Computación e Informática",
        "Ingeniería Civil en Obras Civiles", "Ingeniería Civil Industrial",
        "Ingeniería Comercial", "Kinesiología", "Literatura Creativa",
        "Medicina", "Nutrición y Dietética", "Obstetricia",
        "Odontología", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Media", "Periodismo", "Psicología",
        "Publicidad", "Sociología", "Tecnología Médica",
        "Terapia Ocupacional", "Trabajo Social",
    ],
    # ─── Universidad de los Andes (UANDES) ───
    # Authoritative carreras list as provided by the user.
    "Universidad de los Andes": [
        "Administración de Servicios",
        "Derecho",
        "Derecho e Historia",
        "Derecho y Filosofía",
        "Educación de Párvulos con menciones",
        "Enfermería",
        "Filosofía",
        "Historia",
        "Ingeniería Civil Industrial",
        "Ingeniería Civil Eléctrica",
        "Ingeniería Civil en Ciencias de la Computación",
        "Ingeniería Civil en Obras Civiles",
        "Ingeniería Civil Química",
        "Ingeniería Comercial",
        "International Business",
        "Kinesiología",
        "Literatura",
        "Marketing y Publicidad",
        "Medicina",
        "Nutrición y Dietética",
        "Obstetricia y Puericultura",
        "Odontología",
        "Pedagogía Básica con menciones",
        "Pedagogía Básica Bilingüe Inglés-Español",
        "Periodismo y Comunicación Estratégica",
        "Psicología",
        "Terapia Ocupacional",
    ],
    # ─── Universidad de Concepción (UdeC) ───
    "Universidad de Concepción": [
        "Agronomía", "Antropología", "Arquitectura", "Arquitectura del Paisaje",
        "Artes Visuales", "Astronomía", "Auditoría", "Biología",
        "Biología Marina", "Bioquímica", "Contador Auditor",
        "Derecho", "Diseño Industrial", "Educación General Básica",
        "Enfermería", "Filosofía", "Física", "Fonoaudiología",
        "Geofísica", "Geología", "Historia",
        "Ingeniería Ambiental", "Ingeniería Civil", "Ingeniería Civil Agrícola",
        "Ingeniería Civil Biomédica", "Ingeniería Civil Eléctrica",
        "Ingeniería Civil Electrónica", "Ingeniería Civil Industrial",
        "Ingeniería Civil Informática", "Ingeniería Civil Matemática",
        "Ingeniería Civil Mecánica", "Ingeniería Civil Metalúrgica",
        "Ingeniería Civil de Minas", "Ingeniería Civil Química",
        "Ingeniería Civil Telecomunicaciones", "Ingeniería Comercial",
        "Ingeniería Forestal", "Kinesiología", "Matemáticas",
        "Medicina", "Medicina Veterinaria", "Nutrición y Dietética",
        "Obstetricia", "Odontología", "Pedagogía en Ciencias Naturales",
        "Pedagogía en Educación Física", "Pedagogía en Educación Media",
        "Pedagogía en Español", "Pedagogía en Historia", "Pedagogía en Inglés",
        "Pedagogía en Matemática", "Periodismo", "Psicología",
        "Química", "Química y Farmacia", "Sociología", "Tecnología Médica",
        "Terapia Ocupacional", "Trabajo Social",
    ],
    # ─── Universidad Andrés Bello (UNAB) ───
    # Authoritative carreras list as provided by the user.
    "Universidad Andrés Bello": [
        "Administración Pública",
        "Arquitectura",
        "Artes Visuales",
        "Astronomía",
        "Bioquímica",
        "Biotecnología",
        "Cine",
        "Comunicación Escénica",
        "Contador Auditor",
        "Derecho",
        "Diseño de Juegos Digitales",
        "Diseño de Productos",
        "Diseño de Vestuario y Textil",
        "Diseño Gráfico",
        "Ecoturismo",
        "Educación Parvularia",
        "Enfermería",
        "Fonoaudiología",
        "Geología",
        "Ingeniería Ambiental",
        "Ingeniería Bioinformática",
        "Ingeniería Civil Informática",
        "Ingeniería Civil Industrial",
        "Ingeniería Comercial",
        "Ingeniería en Administración de Empresas",
        "Ingeniería en Automatización y Robótica",
        "Ingeniería en Computación e Informática",
        "Ingeniería en Gestión de Expediciones y Ecoturismo",
        "Ingeniería en Logística y Transporte",
        "Ingeniería en Marina Mercante",
        "Ingeniería en Minas",
        "Ingeniería en Seguridad y Prevención de Riesgos",
        "Ingeniería Industrial",
        "Kinesiología",
        "Licenciatura en Historia",
        "Licenciatura en Literatura",
        "Medicina",
        "Medicina Veterinaria",
        "Nutrición y Dietética",
        "Obstetricia",
        "Odontología",
        "Pedagogía en Educación Básica",
        "Pedagogía en Educación Física",
        "Pedagogía en Educación Media en Inglés",
        "Periodismo",
        "Psicología",
        "Publicidad",
        "Química y Farmacia",
        "Sociología",
        "Tecnología Médica",
        "Terapia Ocupacional",
        "Turismo y Hotelería",
        "Ingeniería en Gestión Sustentable de Recursos Acuícolas",
    ],
    # ─── Universidad San Sebastián (USS) ───
    "Universidad San Sebastián": [
        "Arquitectura", "Contador Auditor", "Derecho", "Enfermería",
        "Fonoaudiología", "Ingeniería Civil", "Ingeniería Civil Industrial",
        "Ingeniería Civil Informática", "Ingeniería Comercial",
        "Ingeniería en Construcción", "Kinesiología", "Medicina",
        "Medicina Veterinaria", "Nutrición y Dietética", "Obstetricia",
        "Odontología", "Pedagogía en Educación Básica",
        "Pedagogía en Educación de Párvulos", "Periodismo", "Psicología",
        "Química y Farmacia", "Tecnología Médica", "Terapia Ocupacional",
        "Trabajo Social",
    ],
    # ─── Universidad Mayor ───
    "Universidad Mayor": [
        "Agronomía", "Arquitectura", "Arte", "Bachillerato",
        "Cine", "Danza", "Derecho", "Diseño", "Enfermería",
        "Fonoaudiología", "Geología", "Ingeniería Civil",
        "Ingeniería Civil Industrial", "Ingeniería Civil Informática",
        "Ingeniería Comercial", "Ingeniería en Construcción",
        "Ingeniería Forestal", "Kinesiología", "Medicina",
        "Medicina Veterinaria", "Música", "Nutrición y Dietética",
        "Obstetricia", "Odontología", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Parvularia", "Periodismo", "Psicología",
        "Química y Farmacia", "Tecnología Médica", "Teatro",
        "Terapia Ocupacional", "Trabajo Social",
    ],
    # ─── Universidad Alberto Hurtado (UAH) ───
    "Universidad Alberto Hurtado": [
        "Antropología", "Ciencia Política", "Contador Auditor", "Derecho",
        "Educación de Párvulos", "Filosofía", "Historia",
        "Ingeniería Civil Industrial", "Ingeniería Civil Informática",
        "Ingeniería Comercial", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Media en Historia", "Pedagogía en Inglés",
        "Pedagogía en Lenguaje y Comunicación", "Pedagogía en Matemáticas",
        "Periodismo", "Psicología", "Sociología", "Trabajo Social",
    ],
    # ─── Universidad Católica de Valparaíso (PUCV) ───
    "Universidad Católica de Valparaíso": [
        "Administración Hotelera", "Administración Pública",
        "Agronomía", "Arquitectura", "Biología Marina", "Bioquímica",
        "Comercio Internacional", "Construcción Civil", "Derecho",
        "Diseño", "Educación de Párvulos", "Enfermería", "Estadística",
        "Filosofía", "Física", "Geografía", "Historia",
        "Ingeniería Civil", "Ingeniería Civil Bioquímica",
        "Ingeniería Civil Eléctrica", "Ingeniería Civil Industrial",
        "Ingeniería Civil Informática", "Ingeniería Civil Mecánica",
        "Ingeniería Civil Química", "Ingeniería Comercial",
        "Ingeniería de Ejecución en Control de Gestión", "Ingeniería de Transporte",
        "Ingeniería en Alimentos", "Ingeniería en Construcción",
        "Kinesiología", "Matemática", "Música",
        "Pedagogía en Biología y Ciencias Naturales",
        "Pedagogía en Castellano y Comunicación", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Física", "Pedagogía en Educación Media",
        "Pedagogía en Filosofía", "Pedagogía en Historia y Ciencias Sociales",
        "Pedagogía en Inglés", "Pedagogía en Matemática",
        "Periodismo", "Psicología", "Química", "Sociología",
        "Trabajo Social",
    ],
    # ─── Duoc UC ───
    "Duoc UC": [
        # Administración & Negocios
        "Administración de Empresas",
        "Administración de Recursos Humanos",
        "Contabilidad General",
        "Ingeniería en Administración",
        "Ingeniería en Comercio Exterior y Operación Logística",
        "Ingeniería en Control de Gestión",
        "Ingeniería en Gestión de Ventas",
        "Ingeniería en Logística",
        "Ingeniería en Marketing Digital",
        "Ingeniería en Recursos Humanos",
        # Comunicación
        "Comunicación Audiovisual",
        "Cine",
        "Publicidad",
        "Relaciones Públicas",
        "Periodismo",
        # Construcción
        "Construcción Civil",
        "Dibujo y Modelamiento de Proyectos",
        "Ingeniería en Construcción",
        "Ingeniería en Prevención de Riesgos",
        # Diseño
        "Diseño Gráfico",
        "Diseño de Productos",
        "Diseño de Vestuario",
        "Animación Digital",
        # Informática & Tecnologías
        "Analista Programador",
        "Ingeniería en Conectividad y Redes",
        "Ingeniería en Informática",
        "Ingeniería en Ciberseguridad",
        "Ingeniería en Desarrollo Full Stack",
        "Técnico en Análisis de Datos",
        # Gastronomía y Turismo
        "Administración Gastronómica Internacional",
        "Gastronomía",
        "Ingeniería en Administración Hotelera Internacional",
        "Ingeniería en Turismo y Hotelería",
        # Salud
        "Enfermería",
        "Técnico en Enfermería",
        "Técnico en Farmacia",
        "Técnico en Laboratorio Clínico",
        "Técnico en Odontología",
        "Técnico en Radiodiagnóstico y Radioterapia",
        # Otros
        "Ingeniería en Sonido",
        "Técnico Jurídico",
        "Trabajo Social",
    ],
    # ─── Universidad Finis Terrae (UFT) ───
    "Universidad Finis Terrae": [
        "Arquitectura", "Arte", "Cine", "Derecho", "Diseño",
        "Enfermería", "Ingeniería Civil Industrial",
        "Ingeniería Civil Informática", "Ingeniería Comercial",
        "Kinesiología", "Medicina", "Nutrición y Dietética",
        "Odontología", "Pedagogía en Educación Básica",
        "Pedagogía en Educación Parvularia", "Periodismo",
        "Psicología", "Teatro",
    ],
}
