"""Serve the pre-built app-design preview pages.

These are **static design mocks**, not the live student app. They render
hardcoded sample data and read nothing from the database, so they are safe to
serve without auth and must never be mistaken for ``/student/*``.

Source lives in ``static/machreach_app`` (``app/*.jsx`` components +
``pages/<id>.jsx`` bootstraps). The committed artifacts ``<id>.prod.html`` and
``<id>.bundle.min.js`` are generated by::

    cd landing_build && node build-app.mjs

Regenerate after editing any source file.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

_APP_DIR = Path(__file__).resolve().parent.parent / "static" / "machreach_app"

# Slug -> built artifact. Only pages listed here are servable, so a stray file
# in the directory can never become a route.
_PAGES: dict[str, str] = {
    "dashboard": "Inicio",
    "cursos": "Cursos",
    "focus": "Enfoque",
    "plan": "Plan",
    "notas": "Notas",
    "herramientas": "Flashcards y quizzes",
    "ranking": "Ranking",
    "amigos": "Amigos",
    "reviews": "Reviews",
    "analiticas": "Analíticas",
    "tienda": "Tienda",
    "perfil": "Perfil",
    "perfil-editar": "Editar perfil",
    "ajustes": "Ajustes",
    "cuenta": "Iniciar sesión y registro",
    "setup": "Configuración inicial",
    "recuperar": "Recuperar contraseña",
    "verificar": "Verificar correo",
}

_PAGE_CSS: dict[str, tuple[str, ...]] = {
    "amigos": ("dash.css", "focus.css", "plan.css", "rank.css", "friends.css"),
    "analiticas": ("dash.css", "focus.css", "plan.css", "courses.css", "analytics.css"),
    "cursos": ("dash.css", "focus.css", "plan.css", "courses.css"),
    "focus": ("dash.css", "focus.css"),
    "herramientas": ("dash.css", "focus.css", "plan.css", "courses.css", "analytics.css", "shop.css", "friends.css", "study.css"),
    "notas": ("dash.css", "focus.css", "plan.css", "courses.css", "analytics.css", "shop.css", "friends.css", "study.css"),
    "plan": ("dash.css", "focus.css", "plan.css"),
    "ranking": ("dash.css", "focus.css", "plan.css", "rank.css"),
    "reviews": ("dash.css", "focus.css", "plan.css", "courses.css", "analytics.css", "shop.css", "friends.css", "study.css"),
    "tienda": ("dash.css", "focus.css", "plan.css", "analytics.css", "shop.css"),
    "perfil": ("dash.css", "focus.css", "plan.css", "friends.css", "profile.css"),
    "perfil-editar": ("dash.css", "focus.css", "plan.css", "friends.css", "profile.css", "profedit.css"),
    "ajustes": ("dash.css", "study.css", "plan.css", "friends.css", "profile.css", "settings.css"),
    "cuenta": ("pubtop.css", "auth.css"),
    "setup": ("dash.css", "profile.css", "pubtop.css", "setup.css"),
    "recuperar": ("dash.css", "pubtop.css", "authflow.css"),
    "verificar": ("dash.css", "pubtop.css", "authflow.css"),
}


def available_pages() -> dict[str, str]:
    """Slug -> human label, for the index listing."""
    return dict(_PAGES)


def page_exists(slug: str) -> bool:
    return slug in _PAGES


def render_design_page(slug: str) -> str | None:
    """Return the built HTML for a preview page, or None if it isn't built."""
    if slug not in _PAGES:
        return None
    artifact = _APP_DIR / f"{slug}.prod.html"
    if not artifact.is_file():
        return None
    return artifact.read_text(encoding="utf-8")


def render_live_page(slug: str, data: dict, version: str | None = None) -> str | None:
    """Return the exact Claude app shell wired to server-provided live data.

    The version keys the browser cache. It was a hardcoded string, which meant
    the URL of every bundle stayed identical across deploys — and the service
    worker serves /static cache-first, so a returning student kept running the
    JavaScript from their first ever visit. It tracks the deploy now, so a new
    deploy is a new URL and the cache cannot answer with yesterday's code.
    """
    from machreach_core.config import DEPLOY_VERSION

    version = version or DEPLOY_VERSION
    if slug not in _PAGE_CSS:
        return None
    payload = dict(data or {})
    payload["live"] = True
    encoded = base64.b64encode(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")
    styles = "".join(
        f'<link rel="stylesheet" href="/static/machreach_app/app/{name}?v={version}">'
        for name in _PAGE_CSS[slug]
    )
    animation_styles = ""
    if slug == "perfil":
        from student.db import BANNER_ANIM_CSS
        animation_styles = f"<style>{BANNER_ANIM_CSS}</style>"
    elif slug in ("perfil-editar", "tienda"):
        # These two preview many cosmetics at once, so they need the full
        # animation catalog, not just the equipped banner's keyframes.
        from student.db import BANNER_ANIM_CSS, FLAG_ANIM_CSS
        animation_styles = f"<style>{BANNER_ANIM_CSS}{FLAG_ANIM_CSS}</style>"
    return (
        f'<link rel="stylesheet" href="/static/machreach_landing/v6/theme.css?v={version}">'
        + animation_styles
        + styles
        + '<div id="root"></div>'
        + '<script>window.__MACHREACH_APP__=JSON.parse(new TextDecoder().decode('
        + f'Uint8Array.from(atob("{encoded}"),function(c){{return c.charCodeAt(0)}})));</script>'
        + '<script src="/static/machreach_landing/vendor/react.production.min.js"></script>'
        + '<script src="/static/machreach_landing/vendor/react-dom.production.min.js"></script>'
        + f'<script src="/static/machreach_app/{slug}.bundle.min.js?v={version}" defer></script>'
    )
