"""Serve the pre-built app-design preview pages.

These are **static design mocks**, not the live student app. They render
hardcoded sample data and read nothing from the database, so they are safe to
serve without auth and must never be mistaken for ``/student/*``.

Source lives in ``static/machreach_app`` (``app/*.jsx`` components +
``pages/<id>.jsx`` bootstraps). The committed artifacts ``<id>.prod.html`` and
``<id>.bundle.min.js`` are generated by::

    cd landing_build && node build-app.mjs

Regenerate after editing any source file.
"""
from __future__ import annotations

from pathlib import Path

_APP_DIR = Path(__file__).resolve().parent.parent / "static" / "machreach_app"

# Slug -> built artifact. Only pages listed here are servable, so a stray file
# in the directory can never become a route.
_PAGES: dict[str, str] = {
    "dashboard": "Inicio",
}


def available_pages() -> dict[str, str]:
    """Slug -> human label, for the index listing."""
    return dict(_PAGES)


def page_exists(slug: str) -> bool:
    return slug in _PAGES


def render_design_page(slug: str) -> str | None:
    """Return the built HTML for a preview page, or None if it isn't built."""
    if slug not in _PAGES:
        return None
    artifact = _APP_DIR / f"{slug}.prod.html"
    if not artifact.is_file():
        return None
    return artifact.read_text(encoding="utf-8")
