"""Serve the pre-built, pre-rendered MachReach landing.

The editable source lives in ``static/machreach_landing`` (``MachReach
Landing.html`` + the ``*.jsx`` component files, which load React + Babel
from a CDN for direct preview/editing). The production artifact
``index.prod.html`` is generated by ``landing_build/build.mjs`` (esbuild
bundle + jsdom pre-render) and committed — it ships production React and a
pre-rendered #root, with no in-browser Babel.

Regenerate after editing the source::

    cd landing_build && node build.mjs
"""
from __future__ import annotations

from pathlib import Path

_PROD_HTML = (
    Path(__file__).resolve().parent.parent
    / "static" / "machreach_landing" / "index.prod.html"
)


def render_landing_page(lang: str = "es") -> str:
    # Always serve the committed production artifact. If it's missing, fail
    # loudly rather than silently fall back to the slow dev build — the fix is
    # to run the build, not to ship un-bundled React + in-browser Babel.
    return _PROD_HTML.read_text(encoding="utf-8")
