"""Country-ISO -> primary IANA timezone map.

Used at signup to default a student's timezone based on the country they
pick. Stored on the client (browser) as `localStorage.user_tz` and used
for client-side date rendering everywhere it matters.
"""
from __future__ import annotations

# ISO-3166 alpha-2 -> primary IANA timezone (capital-city / largest-pop pick).
# Multi-timezone countries pick the most common civil time.
COUNTRY_TZ: dict[str, str] = {
    "US": "America/New_York",
    "CA": "America/Toronto",
    "MX": "America/Mexico_City",
    "GT": "America/Guatemala",
    "HN": "America/Tegucigalpa",
    "SV": "America/El_Salvador",
    "NI": "America/Managua",
    "CR": "America/Costa_Rica",
    "PA": "America/Panama",
    "CU": "America/Havana",
    "DO": "America/Santo_Domingo",
    "PR": "America/Puerto_Rico",
    "JM": "America/Jamaica",
    "HT": "America/Port-au-Prince",
    "BR": "America/Sao_Paulo",
    "AR": "America/Argentina/Buenos_Aires",
    "CL": "America/Santiago",
    "PE": "America/Lima",
    "CO": "America/Bogota",
    "VE": "America/Caracas",
    "EC": "America/Guayaquil",
    "BO": "America/La_Paz",
    "PY": "America/Asuncion",
    "UY": "America/Montevideo",
    "GY": "America/Guyana",
    "SR": "America/Paramaribo",
    "GB": "Europe/London",
    "IE": "Europe/Dublin",
    "FR": "Europe/Paris",
    "DE": "Europe/Berlin",
    "IT": "Europe/Rome",
    "ES": "Europe/Madrid",
    "PT": "Europe/Lisbon",
    "NL": "Europe/Amsterdam",
    "BE": "Europe/Brussels",
    "LU": "Europe/Luxembourg",
    "CH": "Europe/Zurich",
    "AT": "Europe/Vienna",
    "DK": "Europe/Copenhagen",
    "NO": "Europe/Oslo",
    "SE": "Europe/Stockholm",
    "FI": "Europe/Helsinki",
    "IS": "Atlantic/Reykjavik",
    "PL": "Europe/Warsaw",
    "CZ": "Europe/Prague",
    "SK": "Europe/Bratislava",
    "HU": "Europe/Budapest",
    "RO": "Europe/Bucharest",
    "BG": "Europe/Sofia",
    "GR": "Europe/Athens",
    "TR": "Europe/Istanbul",
    "RU": "Europe/Moscow",
    "UA": "Europe/Kyiv",
    "BY": "Europe/Minsk",
    "LT": "Europe/Vilnius",
    "LV": "Europe/Riga",
    "EE": "Europe/Tallinn",
    "HR": "Europe/Zagreb",
    "RS": "Europe/Belgrade",
    "SI": "Europe/Ljubljana",
    "BA": "Europe/Sarajevo",
    "MK": "Europe/Skopje",
    "AL": "Europe/Tirane",
    "MT": "Europe/Malta",
    "CY": "Asia/Nicosia",
    "IL": "Asia/Jerusalem",
    "PS": "Asia/Gaza",
    "JO": "Asia/Amman",
    "LB": "Asia/Beirut",
    "SY": "Asia/Damascus",
    "IQ": "Asia/Baghdad",
    "IR": "Asia/Tehran",
    "SA": "Asia/Riyadh",
    "AE": "Asia/Dubai",
    "QA": "Asia/Qatar",
    "KW": "Asia/Kuwait",
    "BH": "Asia/Bahrain",
    "OM": "Asia/Muscat",
    "YE": "Asia/Aden",
    "AF": "Asia/Kabul",
    "PK": "Asia/Karachi",
    "IN": "Asia/Kolkata",
    "NP": "Asia/Kathmandu",
    "BD": "Asia/Dhaka",
    "LK": "Asia/Colombo",
    "CN": "Asia/Shanghai",
    "HK": "Asia/Hong_Kong",
    "TW": "Asia/Taipei",
    "JP": "Asia/Tokyo",
    "KR": "Asia/Seoul",
    "KP": "Asia/Pyongyang",
    "MN": "Asia/Ulaanbaatar",
    "VN": "Asia/Ho_Chi_Minh",
    "TH": "Asia/Bangkok",
    "MY": "Asia/Kuala_Lumpur",
    "SG": "Asia/Singapore",
    "ID": "Asia/Jakarta",
    "PH": "Asia/Manila",
    "MM": "Asia/Yangon",
    "KH": "Asia/Phnom_Penh",
    "LA": "Asia/Vientiane",
    "BN": "Asia/Brunei",
    "AU": "Australia/Sydney",
    "NZ": "Pacific/Auckland",
    "FJ": "Pacific/Fiji",
    "ZA": "Africa/Johannesburg",
    "EG": "Africa/Cairo",
    "MA": "Africa/Casablanca",
    "DZ": "Africa/Algiers",
    "TN": "Africa/Tunis",
    "LY": "Africa/Tripoli",
    "NG": "Africa/Lagos",
    "KE": "Africa/Nairobi",
    "ET": "Africa/Addis_Ababa",
    "GH": "Africa/Accra",
    "TZ": "Africa/Dar_es_Salaam",
    "UG": "Africa/Kampala",
    "ZW": "Africa/Harare",
    "ZM": "Africa/Lusaka",
    "MZ": "Africa/Maputo",
    "AO": "Africa/Luanda",
    "CD": "Africa/Kinshasa",
    "CG": "Africa/Brazzaville",
    "CM": "Africa/Douala",
    "SN": "Africa/Dakar",
    "CI": "Africa/Abidjan",
}


def tz_for_country(iso: str) -> str:
    """Return the primary IANA timezone for an ISO country code.
    Falls back to UTC if unknown."""
    if not iso:
        return "UTC"
    return COUNTRY_TZ.get(iso.upper()[:2], "UTC")
